### ISSUE TITLE
Standardize GAReference.name for the benefit of other APIs

### ISSUE THREAD

**Issue by cassiedoll** [ga4gh/schemas#112]
We currently have 2 APIs that are tangentially related to our main v0.5 - [beacon](https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/beacon.avdl) and [matchmaker](http://cassiedoll.github.io/matchmaker-staging.html#/schema/target%2Fschemas%2Fmatchmaker.avpr/org.ga4gh.match.GAGene). And in each of those APIs, there is a concept of a chromosome field, which is currently a string in both cases. 

It would be good to help these other APIs benefit from GAReference and introduce some standardization. 

Possible solutions:
- We add comments to GAReference.name explaining exactly how the name should be formatted (with a 'chr' prefix or number-only, etc)
- GAReference.name becomes a different GA object which beacon/matchmaker/others can reuse
- Beacon/matchmaker somehow use real fully defined GAReference.ID fields, which we teach people how to understand (example value: `http://www.googleapis.com/genomics/v1beta/references/{id}` or `http://trace.ncbi.nlm.nih.gov/Traces/gg/references/{id}`)

Thoughts?

**Comment by delagoya** [comment]
Closing in preference of #167
