### ISSUE TITLE
GAReferenceSet::assemblyId definition needs more rigor

### ISSUE THREAD

**Issue by calbach** [ga4gh/schemas#127]
I tried to improve this comment myself but so far I've come up with:
- It might look like 'GRCh37'
- NCBI uses this as the title when [displaying information for an assembly](http://www.ncbi.nlm.nih.gov/assembly/GCF_000001405.26/).
- It probably corresponds to SAM's @SQ AS value: `Genome assembly identifier`.

Remaining unknowns:
- Is this actually intended to be a stable ID, or is it more of a display name?
- Who is allocating these IDs? Where would I look them up?
- Are there any guarantees of uniqueness?
- What is the relation to an accession ID and why have both?

I apologize if these are basic questions which are answered somewhere, but I've not found a definitive answer on the subject after searching for some time.

```
/** Public id of this reference set, such as `GRCh37`. */
union { null, string } assemblyId = null;
```

**Comment by delagoya** [comment]
Closing this issue due to lack of input and PR. Please reopen if it is still and issue with specific PR
