### ISSUE TITLE
GA4GH APIs need to address scientific reproducibility (propose immutable datatypes)

### ISSUE THREAD

**Issue by benedictpaten** [ga4gh/schemas#142]
Consider a researcher who writes a script against the GA4GH APIs, accesses data and publishes the results. The current APIs do not guarantee that subsequent researchers will get the same result when running the original script, therefore the published results are not assured to be reproducible. 

If GA4GH APIs are to really going change the way bioinformatics is done they need to facilitate the reproducibility of results. In order for results to be reproducible one needs to be able obtain the exactly the same data and associated metadata that were used in an experiment.  For the GA4GH APIs this means that every time a given data object is returned it is always the same. This means that APIs must present data as immutable.  Data objects are never modified, instead new derived versions are created.

Mark Diekhans, David Haussler and I think this is important to address and that it would be relatively straightforward to implement immutability into an update of the v0.5 API. What do people think?

**Comment by delagoya** [comment]
Closing this issue for lack of PR or recent comments. It seems that #167 takes precedence for this issue.

**Comment by awz** [comment]
@delagoya is the Containers and Workflows task-team working on this issue?  Maybe wait until they make progress before closing this issue?  It seems to be pretty important and have quite a lot of content that is referenced by #167.   Also pinging  @fnothaft and @tetron since they may feel happy to close this.
