### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by skeenan** [ga4gh/schemas#148]
**Proposed topic for ASHG** 
So far we have been ignoring Auth. But we all know that in the real world a large fraction of. Are there parts of an auth model that should be standardised - or not - and how would we do that.

**Comment by delagoya** [comment]
Closing in favor of Oauth discussions and implementation from  ga4gh/server#31
Authentication will be resource specific and not a part of the API at this point. 
If someone disagrees, please reopen the issue with a specific example as a new issue/PR
