### ISSUE TITLE
Execution environment

### ISSUE THREAD

**Issue by skeenan** [ga4gh/schemas#149]
**Proposed topic for ASHG**
Execution environment - code touching the data - where do we stand on actually processing the data? Currently we have an REST API which is good for fetching and storing data. But in terms of actually running analysis, there are a lot of approaches. It would be good to tease out the overall vision of that - how do we envision that working.
* e.g. here is a proposed new API, that when given a readSet identifier, will call variants and do something with the output.
* Perhaps the GA4GH github should have more pieces of example code/client libraries where one of them would be a whole processing stack.
* Need to figure out mechanism to delegate to distributed execution engines such that that one could have some consistency between them.
* Reproducibility, Versioning. Consistent name-spacing and how do we execute against data.

**Comment by delagoya** [comment]
Closing for lack of comments in a few months. Open again if needed.
