### ISSUE TITLE
Synchronisation tools

### ISSUE THREAD

**Issue by skeenan** [ga4gh/schemas#150]
**Proposed topic for ASHG**
Synchronisation tools. There are tools within the Hadoop ecosystem to pull down data one is missing. How do we synchronise data between distributed repositories? How do we cache data, handle local copies/remote copies in a multi-cloud world?

**Comment by delagoya** [comment]
Closing does not prevent view of this issue. 
Issue #167 covered a bunch of the issues and is closed.
The following project holds an implementation of digests with set examples to talk around: https://github.com/massie/gastore 

Finally the  newish "Disgests, Containers, Workflows" working group will create a separate repository (or use the one above) to have timely and relevant discussion around.
