### ISSUE TITLE
GASearchVariantsRequest search by alternate allele

### ISSUE THREAD

**Issue by mfiume** [ga4gh/schemas#161]
The existing API does not support specification of an allele (e.g. "A") in a GASearchVariantsRequest.

In order to find matches to a specific variant (i.e. by reference, position, and allele) one must search by the first two and iterate through the results to identify matches with strings in the "alternateBases" array.

**Comment by skeenan** [comment]
This was opened in October and hasn't had a comment since. I'm closing this in 2 days.

**Comment by skeenan** [comment]
Closing. This can be reopened if necessary.
