### ISSUE TITLE
Globally Unique Content Digest

### ISSUE THREAD

**Issue by delagoya** [ga4gh/schemas#167]
### Globally Unique Content Digest

This issue is for broader discussion with the developer community regarding **Globally Unique Content Digests* for identification of data objects and data sets that are currently being defined by the various schema.

The overarching goal is to provide an API centric method to be able to identify a set of data across different data providers or repositories of genomic data sets, so that researchers are able to identify exactly a data set that may have different versions. For example, there are many sequence data sets derived from the NA12878, alignments to different reference genomes, and variant analyses from these alignments. Each of the reference genomes, source sequence sets from sequencing a library, the resulting alignment sets, and variant calls should have some data digest to unambiguously identify it across repositories.

### Tenents

Any version of any set of genomic data in the world can have a digital digest.

**digests are unique**:
: no copy of a data set (data + metadata) will ever have a different digest, and no two different data sets will ever “collide” by accidentally getting the same digest

**digests are privacy preserving**
: given only the digest you can’t determine anything significant about the genomic data set it identifies, unless you are also authorized to use that digest to retrieve the data itself

**digests are decentralized**
: they're not assigned by any central authority; each organization that handles genomic data sets can generate the digests themselves

**digests are unforgeable**
: requesting the data with an ID should be deterministic. If you are not able to recompute the same digest from the the received data set then something went wrong

**accessions and digests are not mutually exclusive**
: accession numbers are widely used in biological data repositories and represent stable identifiers for data sets. Accessions can be assigned to a data set that also has a digest, the difference being that digests are computable from the data, whereas accessions are not computable from the data, but rather rely on the source repository that assigned the accession to the data set.

### Issues effected

Other issues that may be effected by this one:

- #159 : Best practices for joining NGS-derived & clinical variation databases
- #150 : Synchronisation tools
- #143 : Content (Data) management lifecycle
- #142 : GA4GH APIs need to address scientific reproducibility (propose immutable datatypes)
- #112 : Standardize GAReference.name for the benefit of other APIs

----

The original thread from the GA4GH Data Working Group mailing list is located at [https://groups.google.com/forum/#!topic/ga4gh-dwg/Baz7hMjytQg](https://groups.google.com/forum/#!topic/ga4gh-dwg/Baz7hMjytQg).

**Comment by awz** [comment]
@delagoya Any reason this is being closed?

**Comment by delagoya** [comment]
I closed for two reasons: 

1. No comments or work done on the issue since Nov 20, 2014. 
2. No associated Pull Request. 

We can reopen it, but I would rather that there be actual PR or repositories to point to other than a dated issue with no PR. For example, should we just point to [massie/gastore](http://github.com/massie/gastore) as the working document for these issues, and when the group feels that it is ready, promote that work to actual PR on this repository?

**Comment by awz** [comment]
AFAIK - the containers and workflows task team (aka the digests, containers & workflows task team) was going to try and work on this problem.   It would be great to see this content replicated on their mailing-list.   CCing  @fnothaft @tetron

**Comment by pgrosu** [comment]
What is the mailing list for the "Disgests, Containers, Workflows" team?  Is there a Github location for the team?

Thank you,
Paul

**Comment by tetron** [comment]
@pgrosu https://groups.google.com/forum/#!forum/ga4gh-dwg-containers-workflows

**Comment by pgrosu** [comment]
Thank you Peter, I just applied to join it.

Paul
