### ISSUE TITLE
Multiple alts per variant?

### ISSUE THREAD

**Issue by brendanofallon** [ga4gh/schemas#169]
I'm curious to hear people's opinions regarding whether or not a variant can or should encompass multiple alt alleles. It seems that version 0.5 of the variants.avdl supports multiple alts per variant, as alt is an array of strings and not a single string.
 FWIW, I think a variant having multiple alts is a bit confusing and leads to some unnecessary complexity. For instance, each alt may overlap different features of interest, will have different annotations, may each be present in distinct sets of samples, etc. This leads to some confusing requirement, for instance, for the set of annotations associated with a multiple-alt variant, only some annotations will apply to each alt allele, and the annotation set would require some sort of mapping back to which alt(s) are tied to the annotation.
  An alternative would be to represent each alt as a separate variant having the same start position, and restrict the idea of variant to being a single chr-pos-ref-alt combination.   
  I realize that it may be a bit late in the game to question this, and that VCFs of course permit multiple alts per variant so it's something people are familiar with... but I do think that it makes life more confusing in several ways, and I'm not sure what the upside is.

**Comment by skeenan** [comment]
This has been dormant since October. I am closing this in 2 days.

**Comment by skeenan** [comment]
Closing. This can be reopened if necessary.
