### ISSUE TITLE
Add a Feature schema for genome annotations (e.g., ENCODE data)

### ISSUE THREAD

**Issue by laserson** [ga4gh/schemas#178]
I have noticed that there does not yet exist a schema for sequence features.  I have been working on such a schema with @tdanford as part of the ADAM project:

https://github.com/bigdatagenomics/bdg-formats/blob/master/src/main/resources/avro/bdg.avdl#L705

Would there be interest in a pull request that adapts this to ga4gh?

**Comment by skeenan** [comment]
Closing.  Resolved by https://github.com/ga4gh/schemas/pull/246
