### ISSUE TITLE
GenotypeToPhenotype Schema

### ISSUE THREAD

**Issue by kellrott** [ga4gh/schemas#196]
The original discussion about the draft Genotype To Phenotype schema started in the https://github.com/cmungall/schemas fork.

The initial draft can be found at 
https://github.com/cmungall/schemas/blob/genotype-to-phenotype/src/main/resources/avro/wip/genotypephenotype.avdl

A pull request with notes about ideas for how the API should be structured can be found at 
https://github.com/cmungall/schemas/pull/1

There is also another discussion about schema ideas at 
https://github.com/cmungall/schemas/issues/2

**Comment by kozbo** [comment]
@bwalsh can this be closed now?

**Comment by bwalsh** [comment]
@kozbo  yes, thank you
