### ISSUE TITLE
Document semantics of "beacon"

### ISSUE THREAD

**Issue by Naburimannu** [ga4gh/schemas#203]
Most of the AVRO files have high-level conceptual overviews, but beacon.avdl doesn't, only explaining the meaning of each field. From those it's possible to infer a probable meaning, but that's failure-prone.

This lack of doc shows up when we're autogenerating schema definitions for server (https://github.com/ga4gh/server/pull/39)

**Comment by skeenan** [comment]
Closing. Resolved by https://github.com/ga4gh/schemas/issues/210
