### ISSUE TITLE
add CIGAR operators for splices

### ISSUE THREAD

**Issue by saupchurch** [ga4gh/schemas#211]
To support explicit splice declaration it is proposed that CIGAR operators be added to support canonical, non-canonical, major, minor and potentially other types of splices.  This issue is to discuss what operators may be needed as well as their implementation.

**Comment by saupchurch** [comment]
It looks like there are two parts of this issue that have been identified:

1) Rename the CIGAR Skip to Splice (or something similar).  This would be done to more properly document how Skip is being used in practice.

2) Categorization of splice sites.  I agree that this does not really properly belong as part of the CIGAR which is focused on the alignment information.  It is desirable to be able to retrieve the set of reads that have splices as well as know the types of those junctions.  This seems to be a task for an API query method rather than the CIGAR.

How do we go about implementing (1)?  Should discussion of (2) continue here, or would it be better to open a new issue for it separate from CIGAR discussion?

**Comment by skeenan** [comment]
This has been dormant since January. Could we have comment on whether this issue is has been resolved. Closing in 2 days unless objected.
