### ISSUE TITLE
Variant annotation conceptual structure discussion

### ISSUE THREAD

**Issue by stevenbrenner** [ga4gh/schemas#214]
This thread is to discuss the conceptual structure and scope of variant annotation schemas.

Currently methods like VEP, SnpEff, Annovar, and Varant provide annotation in the VCF file in ways that embody historical legacy, are constrained by the VCF format, and not broadly extensible.  The purpose of this discussion is to consider the conceptual nature of these annotations, and the degree of complexity we want them to embody (for example, how much locus and haploytype information) before resolving to a detailed schema.

**Comment by kellrott** [comment]
I'm interested to see where this discussion goes. For the Genotype2Phenotype schema ( https://github.com/ga4gh/schemas/issues/196 ) having high level descriptions, like 'TP53 mutation' would allow us to much more easily link phenotypes to variants. 
This is slightly different a straight variant annotation, in that there is no concrete sample and variant call linked to the variant 'concept' (ie talk about 'TP53 mutation' as a biological concept without actually having to point to a specific caller that was run on a particular sample). But that data structure should be comparable to a variant call that was generated (ie 'TP53 mutation is sample_10 as determined by MuTect)

**Comment by jacmarjorie** [comment]
Here's some suggestions based off a clinical decision support db:

Therapeutic variants
* __coding DNA variant__ 
  *genomic variant, protein variant, transcript variant*
  * variant type: substitution, insertion, deletion, deletion/insertion (indel), translocation, inversion, conversion, duplication
  * protein / transcript variant subtypes: nonsynonymous – nonsense, nonsynonymous – missense, synonymous, NULL, in-frame, frameshift
  * variant class: germinline, somatic, unknown
  * variant presense: absent or present
  * variant priority: priority to give the variant based on known clinical protein
 changes, or precedence over conflicting annotations
  * variant source(s): database, variant caller, annotator

* __noncoding variant__

* __copy number variant__ (gain, loss, none)

* __stop gain/loss variants__ (loss of function)

* __functional impact__: gain of function (normal, or low activity), loss of function, reduced kinase activity, switch of function

**Comment by iskandr** [comment]
The word *annotation* seems awfully overloaded in the context of genomics. Is this thread talking specifically about immediate effects such as "deletion of first two intronic residues probably messes with splicing"? Or does this thread also include higher level annotations such as "disruption of this particular binding domain in TP53 is known to be oncogenic"? 

Some suggestions for the modest former case:

1) It's only meaningful to talk about a genomic variant's effect on a particular transcript. The existing conventions of summarizing a variant by its most deleterious effect on any transcript or its effect on the longest transcript are both crude rules of thumb. It's probably desirable to preserve all the transcript-specific effects, even at the cost of moving away from stuffing effect annotations into a VCF. 

2) Annotation programs don't typically make it easy to determine the altered protein sequence for variants other than SNVs (i.e. "V348fs" doesn't tell me much). Please preserve inferred protein sequences for frameshift and stop-loss variants. If start site and splicing prediction programs have reached sufficiently high accuracy, then getting protein sequences for start-loss and splicing variants would also be nice.

**Comment by diekhans** [comment]
variant annotations has been accepted into the schema; I believe this issue is resolved

**Comment by iskandr** [comment]
@diekhans Link to the variant annotation schema?

**Comment by diekhans** [comment]
schema is:
https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/alleleAnnotations.avdl
https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/alleleAnnotationmethods.avdl

**Comment by mbaudis** [comment]
The use of “analysisId” for the “id" of “AnalysisResult” is problematic in that

- an id should just be “id” (as in the rest of the schema), unless it has a specific use/structure (such as ontologyId)
- Named ids are used for referencing the ids of records. Logically, here “analysisId” would provide a reference to the “id” of an “Analysis” record.
- there is an “Analysis” record in metadata



>

**Comment by sarahhunt** [comment]
Hi @mbaudis! analysisId is a reference to the Analysis record in metadata. The AnalysisResult does not have an id of its own.

**Comment by mbaudis** [comment]
@sarahhunt Oh ... I got confused (which may not be a good sign, either for my attention span or the documentation...). I'll delete my comment.

**Comment by sarahhunt** [comment]
@mbaudis - all feedback is useful. I'll have a look at the documentation. We have a nice diagram here - 

http://ga4gh-schemas.readthedocs.org/en/latest/api/alleleAnnotations.html

but it's not very discoverable.
