### ISSUE TITLE
Improve representation of strand

### ISSUE THREAD

**Issue by diekhans** [ga4gh/schemas#218]
The representation of strand as "boolean reverseStrand" in the common.avdl Position record is an uncommon and insufficient way to generally represent strand.  Many genomic features are strand independent and should with a value indicating no strand. Also, programming is more natural when strand is presented as a categorical variable.

Commonly used representations for strand are +/-/. or 1/-1/0.  In my experience, the symbolic version is more intuitive and the numeric version easier to program.

My preference is to use the numeric.

**Comment by jeromekelleher** [comment]
"boolean reverseStrand" sounds clumsy to me too. An enum seems like the natural approach - what would be good values for you?

**Comment by diekhans** [comment]
yes, an enum could be a good approach.

I would suggest pos, neg, none (or it could be nullable for none).

**Comment by laserson** [comment]
How about something like

```
enum Strand {
  Forward,
  Reverse,
  Independent
}
```

**Comment by fnothaft** [comment]
Closed by #237.
