### ISSUE TITLE
Searching for variants only, no calls wanted

### ISSUE THREAD

**Issue by jrobinso** [ga4gh/schemas#221]
It is sometimes useful to query for variant sites alone, without the supporting calls.  In the 1KG project this information would be in a "sites" file,  the full variant + genotypes in a "genotypes" vcf file.  I was looking for a means to do the equivalent via the "variants" search API.   I guessed that supplying an empty array for callSetIds might do it,  although the spec is a little ambiguous here.  However, I tested the following query on the google server and all calls were returned (1092 of them).   Is this a bug in the server, or is this behavior within spec?   If it is within spec,  I would like to request a means to get just the variants.   This is important for datasets with lots of sample, like 1KG.

{"variantSetIds":["10473108253681171589"], "callSetIds":[], "referenceName":"1", "start":"155156300", "end":"155164706", "pageSize":"10000"}

**Comment by pgrosu** [comment]
Hi Jim,

I posted something similar to the `google-genomics` discussion group regarding this some time ago, but reading the method definition for `variants/search`, all the calls should be returned only if `callSetIds` is set to `null` based on [line 66 of variantmethods.avdl](
https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/variantmethods.avdl#L66).  If it is an empty array, then only variants without call objects should be returned.  I guess `null` and an empty array are interchangable in this context, based on the implementation [in line 68](https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/variantmethods.avdl#L68) of the same schema definition, which might have to do more with limitations on Avro's capabilities for defining precise API behavior than anything else.  

I think this would be easy to fix anyway in an implementation.

Paul

**Comment by jrobinso** [comment]
Hmm,  the language is getting confusing here,  but i don't want "variants that do not have call objects",  rather I want "variants only and no calls".    Is that what you understand the spec to provide?

**Comment by jrobinso** [comment]
I definitely think there is some problem here with the language, at least its ambiguous.  The GA4GH says this about the field

Only return variant calls which belong to call sets with these IDs. Leaving this blank returns all variant calls.

The  confusing bit to me is the term "variant calls",  I took it to mean return only those GACall objects that have the supplied IDs in the "calls" field of the variant.   I didn't expect any filtering of GAVariants through this field.   However, googles documentation says this, implying that the filter is on GAVariant objects themselves,  not the "GACall" objects in the calls field.   

Only return variant calls which belong to call sets with these ids. Leaving this blank returns all variant calls. If a variant has no calls belonging to any of these call sets, it won't be returned at all. Currently, variants with no calls from any call set will never be returned.

**Comment by calbach** [comment]
@jrobinso I think you're right about the GA4GH and Google APIs being misaligned on this point. This is likely because the semantics changed recently with #166, which was not part of the [GA4GH v0.5.1](http://ga4gh.org/documentation/api/v0.5.1/ga4gh_api.html#/schema/org.ga4gh.searchVariants).

I believe that in the v0.5.1 API (which Google implements), there is no way of doing what you're describing.

FWIW I don't like `null` and `[]` meaning two different things in the request so I'm not a big fan of that change, though it clearly added desirable functionality to the API..

**Comment by pgrosu** [comment]
Agreed with both, and yes Jim, I interpret it the same as you.  

CH, one thing is that if I miswrite the second `callSetId` on purpose so that it should only match the first one (i.e. `"callSetIds":["10473108253681171589-1","10473108253681111589-0"]`), then I would get the error:

```
API request failed: Invalid value for field "callSetIds": element 1: cannot call SearchVariants across multiple variant sets (400)
```
If I add one additional digit to the second ID (i.e. ` "callSetIds":["10473108253681171589-1","104731082536811111589-0"]`), then I get another error:
```
API request failed: Invalid value for field "callSetIds": element 1: malformed (400)
```
Anyway, lots of stuff to work out.

~p

**Comment by jrobinso** [comment]
Thanks for your responses.  so then the clarification to the spec in https://github.com/ga4gh/schemas/pull/166 would address my request, i.e. it gives a means to suppress return of the calls.  I agree with you its a bit ugly to give this special meaning to [] but it will do the job, when implemented.

**Comment by jeromekelleher** [comment]
This is the semantics offered by the reference server at the moment @jrobinso; we're implementing the 0.5.1 API with a few backports from the current update. See ga4gh/server#34 for discussion on the topic.

**Comment by johntbates** [comment]
I'm also not a fan of there being a semantic difference between empty and null array fields.  This may be an opportunity to explore supporting an optional "fields" parameter and implementing partial responses.  See https://developers.google.com/drive/web/performance for an example of how this might work.  It has the advantages of being optional and supportable across all fields in any response - no field-specific logic or semantics required.

**Comment by jeromekelleher** [comment]
I don't think that there is a special meaning for the empty list in the revised API: specifying zero callSetIds results in a list of zero callsets. The special meaning is attached to null, which results in all callsets.

**Comment by skeenan** [comment]
This has been dormant since January. I will close in 2 days unless objected.

**Comment by jrobinso** [comment]
Well,  I still think this is a real need.   Querying for 1kg data, for example, takes a very long time even if you really just want the sites (not the genotypes).   I think this will be a common use case.

**Comment by jeromekelleher** [comment]
I completely agree with you @jrobinso, but this has been dealt with in the schema. See PR #166.

**Comment by skeenan** [comment]
Thanks @jeromekelleher. Closing.
