### ISSUE TITLE
Method to get varianset by ID?

### ISSUE THREAD

**Issue by jrobinso** [ga4gh/schemas#225]
Hi,  I searched the issues for this.  I would like to fetch a variantset by ID.  I don't see a get method defined in the GA4GH 0.5.1 API documentation,  although the google API defines 

GET  /variantsets/variantSetId

Is this just missing from the documentation, or is it not part of 0.5.1?  In general can we count on a "get" method to retrieve any entity that has an ID?

**Comment by david4096** [comment]
Was added as part of [this commit](https://github.com/ga4gh/schemas/commit/dffa601a31f62a50e637a19178c8d8866d1b0d37)

https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/variantmethods.avdl#L55

    /**************** /variantsets/{id} *******************/
    /**
    Gets a `VariantSet` by ID.
    `GET /variantsets/{id}` will return a JSON version of `VariantSet`.
    */
    org.ga4gh.models.VariantSet getVariantSet(
      /**
      The ID of the `VariantSet`.
      */
      string id) throws GAException;
