### ISSUE TITLE
referenceSetId missing from GASearchReferencesRequest (0.5.1)

### ISSUE THREAD

**Issue by jrobinso** [ga4gh/schemas#227]
Oddly referenceSetId is missing from the fields for GASearchReferencesRequest on the v0.5.1 api.  It does exist in googles implementation.  I assume this is a bug in documentation.

**Comment by calbach** [comment]
It looks like this didn't make it into the v0.5.1 API, but it has since been added to this repository.

https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/referencemethods.avdl#L99

**Comment by david4096** [comment]
Currently documented here: https://ga4gh-schemas.readthedocs.org/en/latest/schemas/referencemethods.html#avro.SearchReferencesRequest
