### ISSUE TITLE
referenceName in Position record should not be a string

### ISSUE THREAD

**Issue by deanasnyder** [ga4gh/schemas#228]
The referenceName field in the Position record (namespace = org.ga4gh.model) should not be a string; it should be a long that maps to the reference name. This would enable orders of magnitude faster processing of these ubiquitous, core records; and would suggest a different name for this field, something like "referenceID".

**Comment by diekhans** [comment]
related to https://github.com/ga4gh/schemas/issues/593

**Comment by diekhans** [comment]
closed in favor of https://github.com/ga4gh/schemas/issues/593
