### ISSUE TITLE
Use cases and implications of Reference.isDerived?

### ISSUE THREAD

**Issue by adamnovak** [ga4gh/schemas#231]
The documentation for `Reference.isDerived` states that:

> Two sequences derived from the same official sequence share the same coordinates and annotations, and can be replaced with the official sequence for certain use cases.

What use cases are these, specifically? Can we give an example of when a derived reference would be used?

Moreover, a derived reference is supposed to be derived from a "source" reference, differing by an amount given in `sourceDivergence`, yes? When a reference is marked derived, how does that change the interpretation of `sourceURI` and `sourceAccessions`? Do they give you the sequence and accessions for the source sequence, or the derived sequence? In either case, where can the other sequence and accessions (if any) be obtained?

Should we have a `sourceID` field for linking derived `Reference`s to their source `Reference`s in the repository?

**Comment by fnothaft** [comment]
See #130 for an extended discussion; I suggest closing this issue as a dupe?

**Comment by adamnovak** [comment]
Yeah that's a dupe, sorry. It didn't show up when I searched.

**Comment by fnothaft** [comment]
No worries!
