### ISSUE TITLE
Query semantics for parent IDs inconsistent and problematic

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/schemas#247]
The structure of the queries for the different aspects of the data hierarchy are inconsistent, with variants, reads and references all having slightly different semantics when it comes to specifying the parent IDs that we are allowed to search over.This is unfortunate and makes implementation difficult. 

We have:

```
SearchReadGroupSetsRequest {
  /** The list of datasets to search. */
  array<string> datasetIds = [];
  // removing rest for clarity
}
SearchReadsRequest {
  /** If specified, restrict this query to reads within the given readgroups. */
  array<string> readGroupIds = [];
  // removing rest for clarity
}
SearchVariantSetsRequest {
  /**
  If specified, will restrict the query to variant sets within the
  given datasets.
  */
  array<string> datasetIds = [];
  // removing rest for clarity
}
SearchVariantSetSequencesRequest {
  /**
  If nonempty, return `Segment`s describing novel sequences in the `VariantSet`
  that are joined onto sequences with one of the specified IDs.
  */
  array<string> parentIds = [];
  // removing rest for clarity
}
SearchVariantsRequest {
  /** Required. The IDs of the variant sets to search over. */
  array<string> variantSetIds = [];
  // removing rest for clarity
}
SearchAllelesRequest {
  /** Required. The IDs of the variant sets to search over. */
  array<string> variantSetIds = [];
  // removing rest for clarity
}
SearchCallSetsRequest {
  /**
  If specified, will restrict the query to call sets within the
  given variant sets.
  */
  array<string> variantSetIds = [];
 // removing rest for clarity
}
SearchAlleleCallsRequest {
  /**
  If nonempty, only return the `AlleleCall`s in these `CallSet`s.
  */
  array<string> callSetIds = [];
  /**
  If nonempty, return only `AlleleCall`s in these `VariantSet`s.
  */
  array<string> variantSetIds = [];
  // removing rest for clarity
}
SearchReferenceSetsRequest {
  // No parent IDs required
}
SearchReferencesRequest {
  /**
  If present, return only references which belong to this reference set.
  */
  union { null, string } referenceSetId = null;
   // removing rest for clarity
}
```

I've lost count here, but I think there are at least four different conventions with different semantics. In short, it's a mess.

I think we should have a single consistent rule that applies to all these queries: where it applies, we have a single, mandatory, parentId. That is, a `SearchVariantsRequest` must specify the `variantSetId`; a `SearchVariantSetsRequest` must specify the `dataSetId`. A `SearchReadsRequest` must specify the readGroupId; a `SearchReadGroupSetsRequest` must specify a dataSetId. A `SearchReferenceRequest` must specify a referenceSetId. (I'm not sure how this fits in with the graph mode  - @adamnovak?)

Why do we want to search across multiple parent IDs? For example, what benefit is it to the client to be able to search for variants across two or more variantSets, when they can easily send sequential requests? The performance gains (if any) would be very marginal and in rare edge cases. Having to support searching across multiple sets makes implementation on the server side _much_ more complicated. 

We must also think about how we are going to support authorisation. I think it would be quite difficult to do properly under the existing model(s). At least with a single ID of the DataObject that the client wants to search over, we can quickly determine whether they have the privileges _before_ executing the query. Otherwise, what do we do when no parentIds are specified? Return data for all sets that the user has access to? What if the user specifies a query in which they have access to some of the sets, but not the others? Do we check them all first, and then run the query? Fail if they don't have access to one of the sets? Silently ignore the sets that they don't have access to? This is a (completely unnecessary) minefield, in my opinion.

If nothing else, a consistent and simple implementation of search queries is more-or-less impossible with the current zoo of conflicting definitions and semantics.

**Comment by richarddurbin** [comment]
+1 for rationalising the method specs as requested by Jerome.

Making all searches act on a single object seems to me like making them methods of the object class, which makes sense and supports authentication naturally.
We need to care about authentication.  That is necessary for clinical use and I suspect a key feature of the GA4GH API that will drive its adoption.

Richard

On 5 Mar 2015, at 17:04, Jerome Kelleher <notifications@github.com> wrote:

> The structure of the queries for the different aspects of the data hierarchy are inconsistent, with variants, reads and references all having slightly different semantics when it comes to specifying the parent IDs that we are allowed to search over.This is unfortunate and makes implementation difficult.
> 
> We have:
> 
> SearchReadGroupSetsRequest {
>   /** The list of datasets to search. */
>   array<string> datasetIds = [];
>   // removing rest for clarity
> }
> SearchReadsRequest {
>   /** If specified, restrict this query to reads within the given readgroups. */
>   array<string> readGroupIds = [];
>   // removing rest for clarity
> }
> SearchVariantSetsRequest {
>   /**
>   If specified, will restrict the query to variant sets within the
>   given datasets.
>   */
>   array<string> datasetIds = [];
>   // removing rest for clarity
> }
> SearchVariantSetSequencesRequest {
>   /**
>   If nonempty, return `Segment`s describing novel sequences in the `VariantSet`
>   that are joined onto sequences with one of the specified IDs.
>   */
>   array<string> parentIds = [];
>   // removing rest for clarity
> }
> SearchVariantsRequest {
>   /** Required. The IDs of the variant sets to search over. */
>   array<string> variantSetIds = [];
>   // removing rest for clarity
> }
> SearchAllelesRequest {
>   /** Required. The IDs of the variant sets to search over. */
>   array<string> variantSetIds = [];
>   // removing rest for clarity
> }
> SearchCallSetsRequest {
>   /**
>   If specified, will restrict the query to call sets within the
>   given variant sets.
>   */
>   array<string> variantSetIds = [];
>  // removing rest for clarity
> }
> SearchAlleleCallsRequest {
>   /**
>   If nonempty, only return the `AlleleCall`s in these `CallSet`s.
>   */
>   array<string> callSetIds = [];
>   /**
>   If nonempty, return only `AlleleCall`s in these `VariantSet`s.
>   */
>   array<string> variantSetIds = [];
>   // removing rest for clarity
> }
> SearchReferenceSetsRequest {
>   // No parent IDs required
> }
> SearchReferencesRequest {
>   /**
>   If present, return only references which belong to this reference set.
>   */
>   union { null, string } referenceSetId = null;
>    // removing rest for clarity
> }
> I've lost count here, but I think there are at least four different conventions with different semantics. In short, it's a mess.
> 
> I think we should have a single consistent rule that applies to all these queries: where it applies, we have a single, mandatory, parentId. That is, a SearchVariantsRequest must specify the variantSetId; a SearchVariantSetsRequest must specify the dataSetId. A SearchReadsRequest must specify the readGroupId; a SearchReadGroupSetsRequest must specify a dataSetId. A SearchReferenceRequest must specify a referenceSetId. (I'm not sure how this fits in with the graph mode - @adamnovak?)
> 
> Why do we want to search across multiple parent IDs? For example, what benefit is it to the client to be able to search for variants across two or more variantSets, when they can easily send sequential requests? The performance gains (if any) would be very marginal and in rare edge cases. Having to support searching across multiple sets makes implementation on the server side much more complicated.
> 
> We must also think about how we are going to support authorisation. I think it would be quite difficult to do properly under the existing model(s). At least with a single ID of the DataObject that the client wants to search over, we can quickly determine whether they have the privileges before executing the query. Otherwise, what do we do when no parentIds are specified? Return data for all sets that the user has access to? What if the user specifies a query in which they have access to some of the sets, but not the others? Do we check them all first, and then run the query? Fail if they don't have access to one of the sets? Silently ignore the sets that they don't have access to? This is a (completely unnecessary) minefield, in my opinion.
> 
> If nothing else, a consistent and simple implementation of search queries is more-or-less impossible with the current zoo of conflicting definitions and semantics.
> 
> —
> Reply to this email directly or view it on GitHub.
> 




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by pgrosu** [comment]
+1 totally this needs to be revamped.  Again this comes to something I previous posted, but the basic idea is this:

One day you decide to do some analysis and open a Genome Browser accessing all the repositories. There you select several regions of the human genome, and a filter by a specific cancer subtype, while sorting the variants by cancer stage. Then you select the ones that the rarest and what to know which samples they come from.  This combines Matchmaker and Beacon, and like Richard mentioned has a necessary clinical use.

~p

**Comment by adamnovak** [comment]
I think it's a good idea to throw out some of these conventions. However, I
think you might be mixing the notion of a "parent" of a sequence in the
graph (i.e. what it's joined on to) with the notion of what it is contained
in (i.e. its "parent" variant set or reference set).

We can make specifying the container ID mandatory, but the joined-onto ID
needs to be nullable, because sometimes we just want all the sequences
regardless of how they are attached.

**Comment by mbaudis** [comment]
> On 05 Mar 2015, at 20:11, adamnovak <notifications@github.com> wrote:
> 
> in (i.e. its "parent" variant set or reference set).

derivedFrom?

**Comment by jeromekelleher** [comment]
Thanks for clarifying this @adamnovak, I'll make a PR with a proposal.

**Comment by david4096** [comment]
Closed with https://github.com/ga4gh/schemas/pull/253
