### ISSUE TITLE
GAReadAlignment.nextMatePosition not getting written correctly?

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/schemas#262]
The type of `GAReadAlignment.nextMatePosition` ends up in the reference server's `_protocol_definitions.py` as:

`"type": ["null", "GAPosition"]`

When I think it should be:

`"type": ["null", {...schema record of GAPosition...}]`

As seems to be the case for other attributes in `GAReadAlignment`, such as `GAReadAlignment.alignment`.  Those types appear in the generated `GAReadAlignment.avsc` file.

See https://github.com/ga4gh/server/blob/master/ga4gh/_protocol_definitions.py#L589

**Comment by david4096** [comment]
This looks fixed `'nextMatePosition': Position,` [here](https://github.com/ga4gh/server/blob/master/ga4gh/_protocol_definitions.py#L954).

@dcolligan Can we close?

**Comment by dcolligan** [comment]
Yeah, this is outdated.
