### ISSUE TITLE
New topic branch g2p

### ISSUE THREAD

**Issue by nlwashington** [ga4gh/schemas#265]
We would like to introduce a new topic branch for genotype-to-phenotype task team discussion and collaborative work.  Perhaps called simply geno2pheno ?

**Comment by AAMargolin** [comment]
Cool. Maybe just g2p :). Or we can spell out genotype2phenotype, that's good too...

**Comment by pgrosu** [comment]
Sounds great!  Once it's available, please list it since I was out of the loop on Beacon for some time until I found the link for it.

Thanks,
~p

**Comment by nlwashington** [comment]
perhaps @diekhans or @benedictpaten might be able to approve of this?  or does a new topic branch require +1s?  as soon as we get this accepted, we'll be able to make a pull request.

**Comment by buske** [comment]
+1 (for what it's worth)

**Comment by pgrosu** [comment]
@buske, of course all votes are important.

**Comment by diekhans** [comment]
+1. If it's needed.   Really important to get this more viability since in glues together a lot of ga4gh 

-- Sent from my computer phone

-----Original Message-----

**Comment by nlwashington** [comment]
well, we could make a pull request to master; but when reading the "how to contribute" this seemed the safer (even preferred) route.

**Comment by fnothaft** [comment]
Hi all!

I've just created the requested topic branch: https://github.com/ga4gh/schemas/tree/g2p

**Comment by kellrott** [comment]
@fnothaft Can you re-pull master into g2p. Currently g2p is 2 commits behind master, and that is really messing up the file diff for PR https://github.com/ga4gh/schemas/pull/268/, which includes work from the sequence-annotation branch that was just merged into master.

**Comment by adamnovak** [comment]
@kellrot Since #232 never made it in, I think you can just fast-forward the branch yourself.

**Comment by skeenan** [comment]
I have merged master into g2p. diffs should be easier to read now.
