### ISSUE TITLE
Article on the first patients diagnosed with the 100,000 genomes project, and why our project is so critical

### ISSUE THREAD

**Issue by pgrosu** [ga4gh/schemas#308]
Hi Everyone,

Here's a great article about the first patients diagnosed through the 100,000 genomes project:

http://www.genomicsengland.co.uk/first-patients-diagnosed-through-the-100000-genomes-project/

It is a great incentive of why what we are doing is so critical to the rest of the world.

It has been more quiet than usual lately here, so let's keep up the momentum.  We should have a great year ahead of us.

Have a great weekend!
Paul

**Comment by delagoya** [comment]
@pgrosu appreciate the article. Not really a "issue" though so I am going to close this if you don't mind.

**Comment by pgrosu** [comment]
@delagoya No problem, just something interesting and exciting, since we're working in this domain :)
