### ISSUE TITLE
Set string fields to 'String" for java

### ISSUE THREAD

**Issue by wstidolph** [ga4gh/schemas#314]
The default avro plugin behavior is to generate classes with avro 'string' fields as java.lang.CharSequence, which is non-instantiable (abstract). I'm attempting to use the Jackson library to deserialize the GA4GH JSON, and Jackson can't instantiate those fields. There are two ways to fix this - set up custom key deserializers in Jacksan (and any other deserializing library), or change the 'schemas' pom.xml to configure the plugin to generate String fields. I suggest the latter (change the generated class' field type to String)

This can be done by adding to the plugin configuration like this:

    <configuration>
        <sourceDirectory>${project.basedir}/src/main/resources/avro</sourceDirectory>
        <stringType>String</stringType>
    </configuration>

**Comment by mcupak** [comment]
+1

This would be very convenient. CharSequences are very awkward to handle as they don't define reasonable equals/hashCode and String-like utility methods. Many external libraries expect Strings as well so in practice, you most likely end up casting to String anyway.

It should also be noted that String implements CharSequence, so this change is not as aggressive as it might look at first glance.

**Comment by mfiume** [comment]
+1

**Comment by vadimzalunin** [comment]
+1

**Comment by mcupak** [comment]
PR: https://github.com/ga4gh/schemas/pull/370
