### ISSUE TITLE
Add response navigational fields

### ISSUE THREAD

**Issue by wstidolph** [ga4gh/schemas#326]
The schema should include navigational mechanisms in responses. As a client, I want to know how many items are in the total response, and I want to be able to fetch a page (of arbitrary size) starting at any offset in the range.

My immediate example is wanting to keep validation testing snappy ... trying to validate the size of a response, apparently I have to page through the set and count entities on each page. And when I want to do sample-testing to validate data/ordering constraints I'd like to grab data from selected sub-items of the response

This is useful not only as metadata for testing and general navigation, but in a data server it seems that's useful as actual data - the result set size answers "how many X fit the criteria of Y" even without returning the actual data.

**Comment by david4096** [comment]
This is common practice in search APIs I have used, however, it seems like something that could be left up to the implementation. A server might provide the number of results for a given query, but is it necessary to include as part of the schemas? I'd like to close this one, @diekhans @macieksmuga, opinions?

**Comment by mbaudis** [comment]
I think questions like this are now being addressed through Beacon. I support closing.

**Comment by diekhans** [comment]
count queries might be useful, however we don't have good use cases yet in our standard applications.

We really need to get the API out there and drive enhancements via real world use cases.
