### ISSUE TITLE
Matchmaker Exchange API description and linking?

### ISSUE THREAD

**Issue by buske** [ga4gh/schemas#327]
Hi everyone,

Just wanted to ask about the best place to be including and linking the Matchmaker Exchange API efforts within the growing GA4GH ecosystem. Currently, the Avro port of the API is in schemas/.../wip/, with PR #258 updating it and pulling it out into the main schemas directory. 

Assuming the schemas repo is the right place for the MME API Avro port, would it be appropriate to add a note about the MME API Task Team in the schemas README? Or is there a better place for it? At the meetings today, a few people expressed difficulty in tracking down the MME API since it isn't really findable from the top-level GA4GH resources. Perhaps something like the following, either in the schemas README, on the ga4gh.org page, or both?

> ## Matchmaker Exchange Task Team
> The [Matchmaker Exchange (MME)](http://matchmakerexchange.org/) project is focused on building the infrastructure to enable finding similar patients across patient databases, specifically to facilitate the discovery of the genetic causes of rare diseases. It is a federated network of patient databases that are connected through the Matchmaker Exchange API ([main GitHub page](https://github.com/MatchmakerExchange/mme-apis), [Avro port](https://github.com/ga4gh/schemas/tree/master/src/main/resources/avro/wip/matchmaker.avdl)) which enables querying for similar patients based on the phenotypic and genotypic profile of a patient.

**Comment by skeenan** [comment]
Would be nice to have the MME repo up there on the (front page([http://github.com/ga4gh) alongside Beacon and the Server. Would definitely give it more visibility as part of the family. What are the logistics in migrating?

**Comment by buske** [comment]
@skeenan My guess is that it is unlikely will we migrate our main GitHub repo, but it might be a good compromise to have a repo for the GA4GH face of the project and the Avro port? @Relequestual, any thoughts? This is what we could like from the GA4GH page, and it could contain a README with a GA4GH-oriented communication of the project and a pointer to the main repo and the Avro port.

**Comment by Relequestual** [comment]
I nearly wrote a comment yesterday: I've been thinking, I'm not sure what the point of back porting MME to Avro when we've found out that the way the Avro is intended to be used, is incompatible with the MME project at current. Avro json is not compatible with standard json.

**Comment by Relequestual** [comment]
On the subject of a visability though (Sorry for getting sidetracked), I don't see any harm in having a repo there which simply has a readme that directs to the actual repo.

**Comment by diekhans** [comment]
Hi @Relequestual

I would say this a bit different: not all JSON is valid as Avro
JSON.  There are many ways one could express the data in the
schema in JSON, as JSON is a very general structured format.  If we are
going to be interroperable, we need exact definition of the wire
protocol.  If we are going to do this efficiently, we need
parses and validators, not coding by hand.

Avro was not designed to work in the way we are using it.  This
is why many of us have developed the feeling that is the wrong
tool for the job.

**Comment by Relequestual** [comment]
@diekhans Was great to meet you at the plenary last week Mark!

I agree to an extent.
I use json-schema to validate the request and the response.
Each system in the Matchmaker Exchange network already has its own object structure, so manual parsing to convert the request json to a native query, is always going to be needed. I don't see a way round that. Unless that isn't what you mean by parsers in this instance?

**Comment by diekhans** [comment]
Likewise @relequestual, great meeting and working with you.  I
will be at EBI/Sanger, the second half of july, so lets meet
again in person.

An important part of an API specification is precision.  One should
be able to take only the specification and implement a client or server
without any other API-specific dependencies.  This is both the schema
and the underlying wire protocol must be documented and clear.

Having a IDL that makes it easier to both define the wire
protocol and correctly use it.  However, it shouldn't be a
requirement.  One would be able to use json-schema as an
alternative to an IDL.

We are trying to get to this point.

**Comment by Relequestual** [comment]
Agreed on all counts. The major problem with json-schema is the lack of good Perl support. The module supports the majority of draft 3, but no draft 4 support. I'd like to be able to spend some time updating it (I requested and was granted access to do so), but it's a fair emount of work, even to complete draft 3. There's even some uncerntanty as to the potential future of json-schema... It's something the web community needs so I sure hope it doesn't die!

**Comment by pgrosu** [comment]
@Relequestual I understand but would you feel comfortable with writing a small Perl wrapper to launch an implementation written in another language, that's available at the link below:

http://json-schema.org/implementations.html

~p

**Comment by Relequestual** [comment]
@pgrosu It's sure something I would consider. I'm not sure how I'd go about that though.

**Comment by pgrosu** [comment]
@Relequestual It's not that scary, and below is a simple step-by-step example of a wrapper without direct library calling.  For instance, you can use the command-line interface (cli) for the following Python implementation:

https://github.com/johnnoone/json-spec

The documentation for the cli commands is here:

https://github.com/johnnoone/json-spec/blob/master/docs/cli.rst

Below is an example of how to install it, and run a small test example before implementing the Perl wrapper:

```
$ pip install json-spec
$ wget https://raw.githubusercontent.com/johnnoone/json-spec/master/examples/basic.json
$ bin/json validate --schema-file basic.json --document-json='{"firstName": "John", "lastName": "Doe", "age": 99}'
$ echo '{"firstName": "John", "lastName": "Doe", "age": 99}' > basic_example.json
$ bin/json validate --schema-file=basic.json --document-file=basic_example.json
```

The reason I call it from the `bin` directory is because I used a `virtualenv`, but the `json` package should be ready to run once you install it.  Now let's implement the call from Perl, and save it to a file called `perl-validation.pl`:

```
#!/usr/bin/perl

use strict;
use warnings;

validate($ARGV[0], $ARGV[1]);

sub validate {
  my ($schema, $json) = @_;
  my $command = "bin/json validate --schema-file=${schema} --document-file=${json}";
  my @output = `${command}`;
  foreach my $o (@output) {
    print "$o\n";
  }
}
```

Then you can run it like this:

```
$ chmod +x perl-validation.pl
$ ./perl-validation.pl basic.json basic_example.json
```

Hope it helps,
~p

**Comment by Relequestual** [comment]
Hey @pgrosu. This is something we would be doing as part of a web request, and going down into bash from Perl is something none of us would want during a web request. There is a C library (and I understand that perl better supports using C libaries), but again it doesn't have draft 4 support. Good idea though.

I think myself and a colleague will look at updating the Perl module to support draft 4. I've asked the author before, and he is happy for me to add support, just didn't want to do it himself.

**Comment by pgrosu** [comment]
Hey @Relequestual That sounds great!  As they say, all roads lead to Rome :)

**Comment by buske** [comment]
Update: the migration of the MME API repo to under the GA4GH org has been approved on the MME side. Is the GA4GH in support of this?

**Comment by skeenan** [comment]
Excellent. Very happy to hear this. Following up with you via email.
