### ISSUE TITLE
OMIM and Orphanet references in matchmaker.avdl

### ISSUE THREAD

**Issue by mellybelly** [ga4gh/schemas#331]
should be OMIM: rather than MIM:
and Orphanet: rather than Orpha:

see also #165 
We are working on a curie context method for referencing ontology terms that when implemented you can update and/or give feedback on

example curies  from monarch https://github.com/monarch-initiative/dipper/blob/afd2d11bd6356f37333c5514c8d38071e02f1e58/dipper/curie_map.yaml

@cmungall @mbaudis @nlwashington

**Comment by cmungall** [comment]
I believe that tickets should be file directly on the https://github.com/MatchMakerExchange/mme-apis tracker, matchmaker.avdl is readonly and derived from this (by a manual process...?). @Relequestual?

**Comment by buske** [comment]
Hmm, we had some discussion about MIM vs. OMIM back in the day and found MIM to be used more frequently. Noted, will add a ticket to our main repo.

For Orphanet, that is fixed in PR #258 that we're still waiting to merge.

**Comment by buske** [comment]
And yes, @cmungall, it would be best for tickets regarding the main API to be filed on our github repo, but here is fine as well, especially for comments regarding the Avro schema (which I manually derived from our JSON schema).

**Comment by Relequestual** [comment]
It looks like our (Decipher) system uses OMIM. I don't remember our (MME) justification for MIM, but I wouldn't be opposed to changing it. However, Decipher doesn't store disease data against a patient, so it doesn't impact Decipher in regards to MME, so your call.

**Comment by buske** [comment]
@mellybelly It doesn't look like either purl.obolibrary.org/obo/OMIM_136140 nor purl.obolibrary.org/obo/MIM_136140 resolve. Why is OMIM authoritative?

**Comment by shadowtramp** [comment]
It looks like the "well known name" is OMIM.
At least from the perspective of the identifiers.org:
http://www.ebi.ac.uk/miriam/main/mdb?section=browse&startBy=o lists OMIM. There is no entry for MIM

**Comment by david4096** [comment]
Closing, current development can be seen at https://github.com/MatchmakerExchange/reference-server
