### ISSUE TITLE
Validation of the Schemas (#5)

### ISSUE THREAD

**Issue by pgrosu** [ga4gh/schemas#334]
Since this has been something I've been responsible [for some time](https://github.com/ga4gh/schemas/pull/295#issuecomment-98166800),  I'm filing the issue here - as requested by in [#287 for issue 5](https://github.com/ga4gh/schemas/issues/287#issuecomment-111578618) - to get an idea of what I'm working towards, but let me know if this is something that is preferred or you would like a different approach.  The implementation would be more via functional programming approach.  The test examples can be integrated into the formalized language or be run separately.  The asserts will be part of the expected test results give a dataset.

**_Important:_**  Any additions or changes to the schemas would be required by the submitter to also provide some tests to validate the intention.  The tests would include both code and data with instructions on how to perform them.  Also all previous tests would need to be re-run with any such submissions in order to ensure nothing breaks.  Many of the reasoning for such tests have been provided in my previous post here [https://github.com/ga4gh/schemas/issues/323#issuecomment-110227872].

Are we changing the schema definitions to protobuf?  Feel free to contribute so we can decide as a group.

![schemavalidation](https://cloud.githubusercontent.com/assets/6555937/8137555/48a3082a-1112-11e5-9709-b0e7bc1c00b4.png)

Thanks,
Paul

**Comment by delagoya** [comment]
I think folks from @diekhans group may have some input here.

**Comment by pgrosu** [comment]
The more the merrier - it's more fun as a team :)  By the way can we have a list on Github (https://github.com/ga4gh) of the tasks, their status and contributors.  This way folks don't need to periodically keep searching to be in sync with what's going on with GA4GH.

Thanks,
~p

**Comment by diekhans** [comment]
we are in the process of putting together a conformance tool kit to replace the existing, very limited conformance suite.  It's derived from junit.  As soon as we get some more doc together,
we will open it up to more discussion.

**Comment by pgrosu** [comment]
@diekhans Sounds good and look forward to it.

**Comment by Relequestual** [comment]
I've been looking at Swagger quite a lot recently. It has python (and many other languages) support http://swagger.io/open-source-integrations (ahem https://github.com/ga4gh/schemas/issues/343 )

I'm currently using Swagger for defining an internal API, but it looks like a solid way to define your API, including request and response objects. The specification is a bit hard to read, but no more so than AVRO. It has some really nice tooling behind it to (Playground: http://editor.swagger.io )

**Comment by david4096** [comment]
https://github.com/ga4gh/compliance uses the schemas to perform validation. See the import in a [reads related test](https://github.com/ga4gh/compliance/blob/master/cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadGroupSetsGetByIdIT.java#L5), for example. Although we are continuously improving this process, we can now close this issue.
