### ISSUE TITLE
 Documentation to help new users to become implementors using AVRO (from #287, item 2)

### ISSUE THREAD

**Issue by pgrosu** [ga4gh/schemas#344]
I'm opening this issue up, since it's not been posted yet (after the June 15). This is with regards to [#287 for issue #2](https://github.com/ga4gh/schemas/issues/287#issuecomment-111578618).

The first thing keep in mind is that all these data models for the API are just data that is transferred among computers.  An API is a collection of commands - including the structure of the data  - which are the way to interact with using a programming language.  These can be implemented on a server that serves data via requests to it, or clients that connect to the server and provide results back to the user.

So how does Avro fit in this?  So Avro is a way to define structure to a collection of data elements (i.e. data types) that together build a data model.  These can be data models for Reads, Variants, Metadata, Annotation, etc.

To describe each data element I will use the following Avro (version 1.7.7) set of definitions:

http://avro.apache.org/docs/1.7.7/idl.html

The GA4GH DWG schema definitions that are defined using Avro, are the defined data models which can be found here:

https://github.com/ga4gh/schemas/tree/master/src/main/resources/avro

You will notice that in the schemas that each type of data model is defined by two types of files: the data model, and its methods (which just has the additional `methods` in its filename). For instance `Reads` are defined by:

```
 readmethods.avdl
 reads.avdl
```

The data model for reads (`reads.avdl`) defines how reads would be transmitted, while the methods define what queries (requests) and how the returned data (responses) must look like.
##### Avro Syntax

Before delving into the details of the data models and their methods, I would need to describe how one can use Avro to define them.  So through Avro one uses the IDL (Interface Definition Language) as a way of defining how to interface with such data models or methods, and how they should look like.  I will not describe all of Avro but just the relevant parts to get one started with how we use it.  
###### Namespaces

So you will notice that every single one of our data models/methods (avdl) files start with something called a namespace:

```
@namespace("org.ga4gh.models")
```

Basically that allows one to ensure that variables are defined under a specific boundary so as to not collide with other names which look similar.  For instance all variables would extend the namespace as follows:

A `ReadGroup` would really be a `org.ga4gh.models.ReadGroup`
###### Documentation

Next within a definition of a data model is a commented text that describe its purpose.  For instance for Reads we have something that starts with:

```
/**
This file defines the objects used to represent a hierarchy of reads and alignments:

ReadGroupSet >--< ReadGroup --< fragment --< read --< alignment --< linear/graph alignment

* A ReadGroupSet is a logical collection of ReadGroup's.
* A ReadGroup is all the data that's processed the same way by the sequencer.
 There are typically 1-10 ReadGroup's in a ReadGroupSet.
* A *fragment* is a single stretch of a DNA molecule. There are typically
 millions of fragments in a ReadGroup. A fragment has a name (QNAME in BAM
 spec), a length (TLEN in BAM spec), and an array of reads.
 ...
*/
```

These commented sections - which start with `/**` and end with `*/` - are critical to describing how one should interpret the definition of the data models and its variables.
###### The Protocol

You will then notice that there is something called a `protocol` that envelops the whole data model:

```
protocol Reads {

}
```

The protocol is important since it is what defines what is being transmitted, which in this case are Reads.  For JSON-formatting the equivalent would be the following:

```
{
"protocol" : "Reads",
  "types" : [ ],
  "messages" : {
  }
}
```
###### The Imports

Sometimes there are data elements which can be defined once and then used multiple times - which we refer to in programming circles as "not reinventing the wheel".  This is performed via the `import` command and then defining the type of data format the files are in with the corresponding file to load.  Below you will notice that for reads we import the [common.avdl](https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/common.avdl) and [metadata.avdl](https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/metadata.avdl) ones:

```
import idl "common.avdl";
import idl "metadata.avdl";
```

There is the possibility to import a JSON protocol file as such:

```
import protocol "a_json_protocol.avpr";
```

Or a JSON schema file:

```
import schema "a_json_schema.avsc";
```
###### Defining Records and Errors

Now comes the actual fun part of implementing the data models, and this can be performed via the `record` data type.  Each type of data is denoted by a keyword (i.e. `record`, `string`, `int`, etc) but we will get into each a little bit later.  A `record` is a structure that can contain multiple types of data inside it.  An example is a Bank will have customers, accounts, multiple departments, etc.  In our case you will notice that a Read has the following defined records:
- **Program**
- **ReadStats** 
- **ReadGroup** 
- **ReadGroupSet** 
- **LinearAlignment** 
- **GraphAlignment** 
- **Fragment** 
- **ReadAlignment** 

Now let's take a simple one and go through each definition:

```
record ReadStats {
  /** The number of aligned reads. */
  union { null, long } alignedReadCount = null;

  /** The number of unaligned reads. */
  union { null, long } unalignedReadCount = null;

  /**
  The total number of bases.
  This is equivalent to the sum of `alignedSequence.length` for all reads.
  */
  union { null, long } baseCount = null;
}
```

The `ReadStats` record contains the following defined variables:
- **alignedReadCount**
- **unalignedReadCount**
- **baseCount**

You will notice the data types `union` and `long` being used.  Each of these variables are actually defined as **long** which is a type that can be a number in the range from −2147483647 to +2147483647.  The **union** just means that each these variables can either be defined as a **long** or a **null**.  A **null** just means that no value has been assigned yet.  This is useful for transmission since we would not need to transmit any of the variables assigned as **null** in order to save on bandwidth usage and be able to transmit more.  You will also notice that all of them have "= null;" which means they all have a initial default value of `null`.  This way the client that receives this data would preassign all of them `null` and then change the values to what they are set to once receiving a set of reads.  The semi-colon at the end just denotes the end of the definition for that variable.

One should note that it is possible to define errors as well in Avro, in case the record is not properly populated with values according to its definition:

```
error ReadException {
  string explanation;
  int result_code = -1;
}
```

We have not defined errors in our schema definitions.
###### Types and More Types :)

I will try to go through all the types that are available in Avro, so they are available to everyone that would like to contribute to GA4GH.

**Enumeration**

Enumerations are a collection of predefined constants which then can be used as a type.  For instance below is a definition of an enumeration:

```
enum CigarOperation {
  ALIGNMENT_MATCH,
  INSERT,
  DELETE,
  SKIP,
  CLIP_SOFT,
  CLIP_HARD,
  PAD,
  SEQUENCE_MATCH,
  SEQUENCE_MISMATCH
}
```

Then one can utilize this type as follows by referencing it:

```
record CigarUnit {
  /** The operation type. */
  CigarOperation operation;

  long operationLength;

  union { null, string } referenceSequence = null;
}
```

**Primitive Types**

Avro has the standard primitive types of `int`, `long`, `float`, `double`, `string`, `boolean`, `null`, and `bytes`. 

Basically `int` and `long` are just non-decimal numbers where a `long` can take larger ranges of numbers.  `float` and `double` can take decimal types of numbers.  `bytes` are basically bytes of data which are stored as integers ranging from -128 to 127.  `string` is a alphanumeric type which can contain both characters and numbers.  `null` was defined previously.

To understand the definition of the different types of values possible for `int`, `long`, `float`, `double`, `boolean` and `bytes` the following link is helpful:

https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html

**Complex Types**

There are three complex types in Avro: arrays, maps and unions.  I will go through each one:

**_1)_** **Arrays**

An array is a stored collection of data of the same type in an ordered fashion.  Below is an example of how to define an array:

```
array<type>
```

To define an array of strings one would write it as follows:

```
array<string> AnArray = [];
```

Notice that the default here is defined as an empty array via [].

One can also store a multidimensional array (i.e. an array of arrays) as follows:

```
array<array<string>> AnArrayofArrays = [];
```

**_2)_** **Maps**

A map is collection of key:value pairs, which sometimes is referred to as a dictionary.  The key is always a string and the value is the defined type.  A map is a way of look up a value by a key. Below is an example of how to define an array:

```
map<type>
```

To define an map of integers one would write it as follows:

```
map<int> AMap = {};
```

Notice that the default here is defined as an empty array via curly brackets {}.

One can also combine maps with arrays as follows:

```
 /**
  A map of additional read group information.
  */
  map<array<string>> info = {};
```

**_3)_** **Unions**

A union is collection of multiple types that a variable can take, where there are no repeated types.  The first type defined in a union must equal the default value.  Below is an example:

```
  union { null, string } referenceSequence = null;
```

There are other more complexities that can described about Avro, but I will only add the following one regarding changing the namespace:

Similarly, a `@namespace` annotation may be used to modify the namespace when defining a named schema. For example, if one started with a namespace for a protocol and then wanted to change it inside the protocol, one would just need to add it before the utilizing it for the subsequent records as such:

```
@namespace("org.apache.avro.firstNamespace")
protocol MyProto {
  @namespace("org.apache.avro.someOtherNamespace")
  record Foo {}

  record Bar {}
}
```

For more details regarding Avro, please visit the following link:

http://avro.apache.org/docs/1.7.7/idl.html
##### Methods

Now that I discussed the details of Avro for implementing the data models, let me discuss how the methods are implemented - sometimes referred to as the nouns and verbs in a [RESTful](http://stackoverflow.com/questions/27121749/confusion-between-noun-vs-verb-in-rest-urls) web infrastructure.

Each method starts with the title of definition in a URL lookup, which should look something like this - this example was taken from [referencemethods.avdl](https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/referencemethods.avdl#L27-82):

```
/**************** /referencesets/search *******************/
```

Then there will be two records that are defined - a `Request` and a `Response` to that request:

```
/**
This request maps to the body of `POST /referencesets/search`
as JSON.
*/
record SearchReferenceSetsRequest {
...
}

/**
This is the response from `POST /referencesets/search`
expressed as JSON.
*/
record SearchReferenceSetsResponse {
 ...
}
```

The title defines how one would use the method, which in this case would be something like this:

```
http://SomeRepositoryURL/referencesets/search
```

On the web there are two major types of verbs which we use most of the time: `GET` and `POST`.  Below is their definition:

**GET** - Requests data from a specified resource
**POST** - Submits data to be processed to a specified resource

Thus one can use POST to submit data - in the structured format defined by the request `SearchReferenceSetsRequest` - to a URL for querying a server, as such:

```
curl -v -X POST -H "Content-Type: application/json" -POST '{"accessions": ["ABC_123.456"]}' http://SomeRepositoryURL/referencesets/search 
```

In the example above, `curl` is a simple program like a web-browser that perform these operations and receives responses (results) back.

The response will come back in the format as defined by that structure of the `Response` method - in this case `SearchReferenceSetsResponse` - which will look something like this:

```
{
 "referenceSets": [
  {
   "id": "AbcdEFg",
   "referenceIds": [
    "abcd3234",
    "Xyz3248a",
    ...
    ]
  }
 ]
}
```

Hope this helps people get started with contributing to GA4GH and please comment in case I missed anything, or you would like to see more things.

Thanks,
Paul

**Comment by nmcabili** [comment]
Thanks ! very helpful.

**Comment by david4096** [comment]
Closing with the move to protobuf. @pgrosu If you'd like to write another "bioinformatician's welcome to protobuf" we would welcome it!
