### ISSUE TITLE
Could json-schema and json hyper-schema be used for the IDL?

### ISSUE THREAD

**Issue by Relequestual** [ga4gh/schemas#346]
I've been doing auite a bit more research on json-schema since the GA4GH 3rd plenary meeting. Previously I understood that json-schema is for validation of json. However, as part of the json-schema project, there is also json hyper-schema, which allows for the defining of APIs.

This blog post explains it probably a lot better than I can: https://brandur.org/elegant-apis

Although on the json-schema site, the support for hyper-schema seems limited, the information is out of date, and there are a number of clients for most langauges.

The biggest potential issue with json-schema and associated tools is the future of the protocol. It has been essentially orphaned by the people who originally worked on it, however they are open to others picking up the work.

It is an IETF draft, currently at draft 4. The plan was to release a draft 5, being the final request for comments, resulting in the final official v1 of the specification.

(I have no experience with IETF associated RTF specification documents, so if anyone else has, that expeirence could be valuable if others are willing to support it!)

**Comment by Relequestual** [comment]
@delagoya iirc, you said you had experience with defining specifications. Do you know anyone in your circle of associates who may be interested in this, even if it's not directly for GA4GH?

**Comment by wanghaisheng** [comment]
there is a lot api definition languages such as [RAML](https://github.com/raml-org/raml-spec
),[Swagger](https://github.com/swagger-api/swagger-spec)， they do use json schema to define a api instead of avro ,what I learn is that the schema evolution mechanism provided by avro is more promising and it has a mature binary format too.

**Comment by Relequestual** [comment]
It was agreed at the last GA4GH plenary meeting that Avro is not fit for purpose, as the libraries in major languages do not work together, amoung other reasons. Individuals were tasked with evaluating the move to Protocol Buffers. I'm adding to my previous json-schema comments that json hyper-schema allows for definitions of API's.

**Comment by diekhans** [comment]
The data access APIs are going to use protocol buffers V3 which includes a JSON wire format encoding.  Protocol Buffers is a subset of what can be encode in JSON and there are already tools to map ProtBuf V2 to JSON schema.
