### ISSUE TITLE
plan to getting development between schemas and server synced

### ISSUE THREAD

**Issue by benedictpaten** [ga4gh/schemas#356]
On the ref-var call today we discussed how we get from where we are now with GA4GH development to a proper release process, as has previously been discussed on the DWG call, at Leiden and as outlined in:

https://github.com/ga4gh/schemas/pull/353

To make this all work it is essential we get the master branches synced sooner rather than later. To this end, @adamnovak has created the refVar-linear branch that strips out graph,. The plan is that this be the basis of development, and it be pull-requested against master sooner rather than later.

However, @mcvean  brought up the somewhat radical idea of also stripping out G2P, RNA and other features from this branch, just so that master and server were synced sooner. The plan would then be to add these back in progressively as they are integrated into the reference server. I am sympathetic to this pragmatic plan (but know that git will make this process a pain when we come to add the features back in). 

I'd like feedback on this plan. One big advantage of this plan is that we could start making regular small releases as we go along, and work with other implementors to bring their implementations up to speed with released versions as we go.

**Comment by dcolligan** [comment]
I'd be in favor of getting the schemas to as small of a size as possible for a release, and then adding in extra functionality and releasing as we see fit.

Why do you say you "know that git will make this process a pain when we come to add the features back in"?  Git might be our greatest asset in this regard.  In any event, I don't anticipate it standing in the way...

But in general, I highly favor fast incremental development over waterfall development; it seems like most of software engineering is moving in that direction as well.

**Comment by benedictpaten** [comment]
On Wed, Jul 8, 2015 at 6:44 PM, Danny Colligan <notifications@github.com>
wrote:

> I'd be in favor of getting the schemas to as small of a size as possible
> for a release, and then adding in extra functionality and releasing as we
> see fit.
>
> Why do you say you "know that git will make this process a pain when we
> come to add the features back in"? Git might be our greatest asset in this
> regard. In any event, I don't anticipate it standing in the way...
>
Okay, my bad, I was just thinking that if you delete stuff you've
previously added, then if you merge again the delete will appear in the
history after the original creation during the merge, persisting the delete.

**Comment by jeromekelleher** [comment]
This sounds like a pragmatic and sensible plan to me.  If we want to get users writing code against this API, we need to release an updated schema (based on the last year of work) which can respond to users requirements as they find issues with it. A timely release of the more mature parts of the API, followed by incremental updates is the best way to do this, in my view.

**Comment by haussler** [comment]
sounds right to me

**Comment by diekhans** [comment]
Benedict Paten <notifications@github.com> writes:
> However, @mcvean brought up the somewhat radical idea of also stripping out
> G2P, RNA and other features from this branch, just so that master and server
> were synced sooner

This is an excellent suggestion.  It will most likely speed up
development for the work moved to the topic branch, as
everything little change will not need to be reviewed piecemeal.

**Comment by skeenan** [comment]
I support the end goal of Gil’s proposal. However, w.r.t to the execution of plan I don’t agree that the G2P, Variant Annotation etc need to be stripped from master to make the release when it would be straightforward to create a release branch that includes only the subset of APIs desired for said release.

**Comment by shadowtramp** [comment]
My 2 cents on releases in branch vs releases in master.
From the experience of the maintenance of the previously released standard<->server versions it is far better to maintain branch. Then all minor fixes that are to be made to both standard and server may be made without affecting master development.
That's an alternative approach. I would like to point two positive sides to it:
1. If one need to make minor changes to standard-server, there is no need to make this revert-to-clean master process again.
2. Features added to master do have far greater visibility. Thus the reaction for thoughts provoking changes will be sooner.

**Comment by benedictpaten** [comment]
Sorry for the confusion, I am not advocating releases from master, I am
advocating that release branches be created from master, and then, as you
say, fixes can be made on the release branch, rather than interfering with
master. The advantage of creating release branches from master rather than
from arbitrary topic branches is clear.

**Comment by shadowtramp** [comment]
Thank you a lot for clarification!
Then I'm completely pro this approach!

**Comment by diekhans** [comment]
releases are now coordinated
