### ISSUE TITLE
metadata branch

### ISSUE THREAD

**Issue by mbaudis** [ga4gh/schemas#358]
This is just a note/reminder that we have moved metadata updates (so far concerning `metadata.avdl`, `ontologies.avdl`) to the separate metadata branch, e.g. 

```
https://github.com/ga4gh/schemas/blob/metadata/src/main/resources/avro/metadata.avdl
```

While currently most changes are pushed in directly by members of the Metadata Task Team, we encourage non-core MTT developers to comment/do PRs on the code!

**Comment by kozbo** [comment]
@mbaudis can we close this as obsolete?

**Comment by mbaudis** [comment]
@kozbo yes & done.
