### ISSUE TITLE
API call to list references for a readGroup

### ISSUE THREAD

**Issue by danvk** [ga4gh/schemas#362]
See https://github.com/ga4gh/server/issues/486

My proposal would be to add a `/reads/listreferences` API endpoint which returns a list of reference names and IDs for a readGroup. A few situations where this would be helpful:

1. If you want to know in advance whether to request a range of alignments in `chr17` or `17`.
2. If you want to produce a list of references for a user to choose in a UI, ala IGV:

![screen shot 2015-07-13 at 11 42 49 am](https://cloud.githubusercontent.com/assets/98301/8653779/507b019c-2954-11e5-8b9d-0a713a28bbf1.png)

**Comment by calbach** [comment]
This is already possible via `SearchReferences({referenceSetId: readGroup.referenceSetId})` (see `reference.name`).

**Comment by danvk** [comment]
Just to clarify a few things:

1. The released version of the reference server doesn't support this API yet.
2. The version at `HEAD` does, but the example data isn't configured in such a way that you can access references. (see https://github.com/ga4gh/server/issues/509)

```
$ curl --data '{"datasetIds":["dataset1"]}' --header 'Content-Type: application/json' http://localhost:8000/current/references/search | jq .
{
  "nextPageToken": null,
  "references": []
}
```

**Comment by calbach** [comment]
I don't know about the state of support in the reference server - I'm saying that this functionality is already supported by the API spec so I don't see a reason to add any additional methods. Seems the solution here should be to get the existing API working on the reference server.

Also note that `datasetIds` is not a supported field in any version of the GA4GH `SearchReferences` API, as far as I'm aware: https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/referencemethods.avdl#L114

**Comment by danvk** [comment]
I'll close this out, then. Hopefully the reference server supports this API soon.
