### ISSUE TITLE
metadata branch discussion

### ISSUE THREAD

**Issue by mbaudis** [ga4gh/schemas#369]
Updates to the metadata schema are now done on the metadata branch:

```
https://github.com/ga4gh/schemas/blob/metadata/src/main/resources/avro/metadata.avdl
```

We encourage to follow the developments there (which sometimes cut short on the PR-vote-merge procedure), and post comments as part of this issue.

**Comment by kozbo** [comment]
@mbaudis can we close this as obsolete?

**Comment by mbaudis** [comment]
@kozbo Yes & closed.
