### ISSUE TITLE
Further cleanup of the master branch required?

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/schemas#372]
PR #352 removed the graph aspects of the API from master, and made a major step towards syncing up the schemas and the implementation in the reference server. However, there is still a lot in the schemas that has not been implemented in the server, and it would take a large effort to do so.

I would advocate paring back the schemas in master further by removing everything except the core reads, references, variants and datasets APIs. However, we don't want to lose these files that so much work has gone into. Are there topic branches for all of the new features, where development can go ahead? Are there any objections to this temporary cleanup?

The matchmaker and beacon files seem like a special case, since they are not really a part of the main API being defined here. Perhaps these would be better off in their own ga4gh repos (e.g., ga4gh/mme and ga4gh/beacon)? There are good arguments for keeping all the schemas in one repo, and there are also good arguments for keeping smaller, more focused git repositories. I don't have a strong opinion either way, but since we're doing this cleanup I think it's a good time to have the discussion.

**Comment by diekhans** [comment]
The plan that has been discussed is to move these out into
feature branches.   We need to coordinate with each of the
task teams.

In many cases (variant annotations, sequence annotations,
metaadata), there are already topic branches that are ahead of
master.

Adam Novak figured out some git foo for back things out that
prevents conflicts when reintegrating.

Metadata is a weird case were records are going to need to be
moved back into master as-needed basis.

Discussing with the beacon and MME teams to understand their API
goals would be useful.  Are they planning to converge with
the other APIs or remain independent.

**Comment by mbaudis** [comment]
For metadata, I'm in favour of splitting it into a document containing basic attribute definitions in master, and a separate branch working on the more complex objects. 

Michael

**Comment by macieksmuga** [comment]
My plan for going forward with @jeromekelleher's suggested paring-back is:

- create a new branch, `baseline`, that includes only reads/references/variants/datasets. 
- Then create, on top of that branch, other topic branches such as `beacon-baseline` that includes ONLY baseline + the beacon API. In some cases, these topic branches may need to be nested (as I suspect will happen with metadata - for example the `alleleAnnotations` API uses `Analysis` as defined in `metadata` ).

**Comment by jeromekelleher** [comment]
Why not make the baseline branch master @macieksmuga?

**Comment by diekhans** [comment]
It will become a pull request to master.

**Comment by jeromekelleher** [comment]
OK, makes sense. Is this a strategy to minimise the merge hassle when we reintegrate the topic branches?

**Comment by diekhans** [comment]
To give task teams a chance to review in to head off any problems.

**Comment by macieksmuga** [comment]
The re-merge is mostly going to be trivial, thanks to each task team mostly keeping their code in dedicated files. Thanks @diekhans @jeromekelleher for reviewing the plan.

**Comment by buske** [comment]
Please feel free to remove the awkward `matchmaker-v1` tag on the schema repo as well. This was the recommended way to release our first version way back when, but this doesn't seem to be the preferred method anymore. It seems like it is best for us to version our API in our repo, and have each release get ported to the schema repo for eventual inclusion.

**Comment by macieksmuga** [comment]
@buske thanks! However I think we should let the tag stay where it is - it represents a particular point in time of the repository, and as such helps us understand the history of the development process without affecting future work. Please do carry on the matchmaker team's work in a development branch for now, with the intention of integrating back into the master once the server + compliance repositories are synced up.

**Comment by jeromekelleher** [comment]
Closing this as #373 has been merged.
