### ISSUE TITLE
Dataset should include a name

### ISSUE THREAD

**Issue by macieksmuga** [ga4gh/schemas#394]
Currently the only fields in Dataset are id (server-generated) and description.
A name field would be useful for searches and quick identification.

VariantSets currently don't include a name either, but they have a flexible VariantSetMetadata key-value list that could be used to record such a name.

 I don't have my heart set on any particular way of implementing this, so long as it's relatively consistent between the different fundamental data structures.

**Comment by jeromekelleher** [comment]
This seems like a clear win to me @macieksmuga: it makes the API more consistent, and does not introduce any breaking changes. Is there a PR in the pipelines?

**Comment by mbaudis** [comment]
Here you go:

https://github.com/ga4gh/schemas/pull/399

Also, pls. have a look at https://github.com/ga4gh/schemas/pull/397

**Comment by dglazer** [comment]
@mbaudis -- closing, since #399 is now committed, and #397 is open -- feel free to reopen if there's more to discuss here.
