### ISSUE TITLE
Visualizing GA4GH schema

### ISSUE THREAD

**Issue by lh3** [ga4gh/schemas#402]
Echoing @diekhans' comment, a colleague of mine asked whether there is a visualized schema for GA4GH. I don't know how to draw a diagram for Avro (after some google searches), but I know there are tools to visualize SQL schemas, so I made one to capture the first-class objects:

![ga4gh-sql-v1](https://cloud.githubusercontent.com/assets/480346/9690858/ecf89ba6-530c-11e5-9d97-7cb094cbef69.png)

Note that the SQL schema is not a loyal representation of our Avro schema, because:
1. It is difficult to convert some Avro relationships (e.g. embedded arrays) to SQL as is. 
2. I have changed some parts based on my preferences.

**Comment by diekhans** [comment]
Adam Novak wrote some code to generate UML diagrams from the schemas:
     https://github.com/ga4gh/schemas/blob/master/doc/uml.svg

The intention is to include something based on this in some upcoming
documentation work.

**Comment by haussler** [comment]
Yes.  Heng's image looks a lot more appealing than the UML diagrams I've
seen before.

**Comment by jeromekelleher** [comment]
This is really useful @lh3, thanks! This schema make a lot of sense to me.

One minor point: why not ``referenceId`` in Variant instead of ``refName``?

**Comment by lh3** [comment]
> why not referenceId in Variant instead of refName?

Just followed the current schema without much thoughts. Yes, that is a mistake. The image is updated, along with refName in ReadAlignment changed to referenceId as well.

**Comment by diekhans** [comment]
This is a lot better than the automatically generated UML, although conversion to SQL is a bit of difficult to maintain process.  We can have one of our people look around for a good direct UML tool.  

@lh3, what tool did you use for this.

**Comment by lh3** [comment]
I am using [MySQL Workbench](https://dev.mysql.com/downloads/workbench/). The editable file underlying this image is [here](http://lh3lh3.users.sourceforge.net/download/ga4gh-sql-v1.mwb). Manually created image helps to highlight the key relationships between primary objects. Nonetheless, @adamnovak's UML diagram still looks nice. It may be worth generating a new one for the much simpler schema at master. It will look cleaner now.

**Comment by reece** [comment]
Andrew Jesaitis created these in Gliffy:

![ga4gh_variant_annotation_schema](https://cloud.githubusercontent.com/assets/109453/11026887/8e9607f2-8664-11e5-9811-96bf721e9e0a.png)

[ga4gh_variant_annotation_schema.svg](https://files.zenhub.io/56403738c2cd6a204289cf03)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by ttriche** [comment]
that's terrific!  I didn't even realize GA4GH had a wiggle class for
feature annotations.

--t

**Comment by david4096** [comment]
Will close when something like https://github.com/malisas/schema-uml has been added to the documentation generation toolchain.

**Comment by kozbo** [comment]
closed with #756
