### ISSUE TITLE
Integrate documentation development

### ISSUE THREAD

**Issue by diekhans** [ga4gh/schemas#411]
This serves as the master ticket for bring the documentation topic branch to sufficient maturity to merge into master.

The following process is proposed to managing the edits
- Tickets will be created and those knowledgeable of the various different functional areas will be recruited to improve the documentation.
- Tickets will have the _Documentation_ label and the _comprehensive doc_ milestone.
- Edits will be done in forks and a pull requests made to the documentation branch, not the master.
- @diekhans will act as build manager for the project, merging pull request into to the documentation branch.
- Simple changes can be merge immediately
- More complex changes will have discussion and voting following the standard process.
- The build manager will periodically manually review the generated documentation after major merges to help ensure the layout remains correct.
- The build manager will create PRs to merge the documentation to master when all tickets have been cleared or differed.

**Comment by jeromekelleher** [comment]
Sounds good to me. +1 on the process.

**Comment by dglazer** [comment]
+1 on the process, and thank you @diekhans for volunteering to be the build manager. Two small points below.

> The build manager will periodically manually review the generated documentation after major merges to help ensure the layout remains correct.

If you can, please make sure there's an easy way for people to find that generated documentation, including some way to know when it was generated. (So we can know which of our changes have already been incorporated.)

> The build manager will create PRs to merge the documentation to master when all tickets have been cleared or differed.

Sounds good, with the clarification that you should feel free to create some of those merge PRs before *all* the tickets have been cleared -- it may make sense to merge in parts of the branch earlier than others.

**Comment by diekhans** [comment]
Thanks @dglazer

Travis CI runs when documentation is committed.  However, I
think it will take a cron job to actually make public
documentation.

**Comment by skeenan** [comment]
The content of the emerging documentation is great and thanks for all your
work on this. Would be appropriate if the  aforementioned cron job produced
documentation with look and feel of http://github.com/ga4gh/dwg-website

**Comment by jeromekelleher** [comment]
[Deployment with Travis](http://docs.travis-ci.com/user/deployment/) might be a better option than a cron job running on someone's server.

**Comment by david4096** [comment]
The build process currently uses jenkins https://travis-ci.org/ga4gh/schemas/builds/176489891
