### ISSUE TITLE
Proposed Solution for Uncallable Genotype in Call object

### ISSUE THREAD

**Issue by jacmarjorie** [ga4gh/schemas#428]
A genotype is defined as a list of ints: https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/variants.avdl#L132-L146. Though, sometimes a call doesn't have a genotype. It would be nice to get consensus on how people are representing the genotype: ./.

Our group has proposed: [-1,-1] only to comply with the current type.

What have others done? And if a consensus is made, this should be added to the documentation.

**Comment by jjfarrell** [comment]
Looks like this issue has been discussed before but never made it to the schema documentation.
https://github.com/ga4gh/server/issues/14

The discussion also thought using -1 for uncalled genotypes was a good approach.

**Comment by david4096** [comment]
Picked up here https://github.com/ga4gh/schemas/issues/727
