### ISSUE TITLE
0.6.0 release requirements?

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/schemas#434]
Releasing a 0.6.0 alpha version of the schemas has been discussed and it has been generally agreed that we would like to do this before the meeting at NYGC next week. The release is not intended for general use, but is an early alpha which we can incrementally improve on in subsequent regular  0.6.x point releases.

What do we need to do before we can tag 0.6.0? Here are some things that need to be done:

1. Create a detailed change log from 0.5.1 to 0.6.0. (This is a substantial chunk of work.)
2. Update the documentation on ga4gh.org to point to the Avrodocs for the current head of master. (We should probably keep the 0.5.1 documentation alive also.)

Does everyone agree with this process? Are there any other tasks that need to be done before we can tag the release? Who is going to take care of these issues?

**Comment by skeenan** [comment]
I will take care of #2

**Comment by heuermh** [comment]
Was this issue closed prematurely?  See e.g. #278
