### ISSUE TITLE
Variant annotations: AnnotationSet should point to VariantSet instead of DataSet

### ISSUE THREAD

**Issue by pcingola** [ga4gh/schemas#439]
This issue is for the variant annotations branch.

Currently the structure makes it difficult to retrieve the variantSet since we must go all the way up to the DataSet and match (possibly more than one) the VariantSet:

    record AnnotationSet {
      /** The ID of the annotation set record */
      string id;
      /** The ID of the dataset to which this annotation set belongs */
      string datasetId;

A simple change to a variantSet handle instead of a dataSet handle would improve the situation:
 
    record AnnotationSet {
      /** The ID of the annotation set record */
      string id;
      /** The ID of the variantSet to which this annotation set belongs */
      string variantSetId;

**Comment by calbach** [comment]
I definitely disagree with **changing** it, though a variant set ID field could certainly be added to the annotation set provenance. It would not make sense in general for an annotation set to belong to a variant set.

**Comment by pcingola** [comment]
Could you elaborate on why "it would not make sense"?
Everyone in today's call seemed to agree that it would be best to change it.

**Comment by calbach** [comment]
I assumed this was referring to the [annotations branch](https://github.com/ga4gh/schemas/tree/annotations) which models arbitrary sequence annotations, e.g. Genes (which clearly won't necessarily 'belong to' a variant set). Could you link to a specific line to clarify?

**Comment by pcingola** [comment]
Actually this refers to the "variant annotations" branch.
Apologies for the confusion, I should have clarified it in the title.

**Comment by pcingola** [comment]
Changed the issue's title, I hope it is less confusing now.

**Comment by diekhans** [comment]
in general, `AnnotationSet' is a confusing name.  I would encourage naming this VariantAnnotationSet.  Annotation is a very general term that means different things in different genomics contexts.

**Comment by pcingola** [comment]
I'm OK with changing the name, but this should probably 
be discussed as a separate issue...

**Comment by sarahhunt** [comment]
Hi Pablo,

I've had a look at this, and querying for annotation across many variant 
sets was the original intention.

The proposed change would make the use case of 'I'm interested in this 
gene - what variants are in the region?' more tedious for the client. 
You would need to issue multiple queries for each 1KG, ClinVar, ESP, 
ExAC, etc VariantSet and filter through them all though the results from 
each query would overlap heavily.

That said, the change gives the user a clearer idea of provenance/data 
quality and fits better with the concept of a dataset as a container for 
reads which can be submitted to different calling proceedures to make 
different variant sets.

Out of interest - how does the backend you are planning relate to the 
model? Is a VCF with annotation an annotation set?

**Comment by pcingola** [comment]
We would still have access to dataSetId, it's just indirectly accesses using 
VariantSet instead of directly accesses using AnnotatiaonSet:

    AnnotationSet -> VariantSet -> DataSet

So the queries across variantSets within a dataSet can still be performed. 

In the current schema, a Variant belongs to one and only one VariantSet. So 
the case you mention would not be affected. E.g. if a variant (e.g. "chr1:1000_A/T") 
is in all VariantSets (e.g. 1KG, dbSNp, ExAC, etc.), then you would need to represent 
it as unique variants in each VariantSet (since each of them has a different 
'variantSetId' field). Thus you would have to create a VariantAnnotation record 
for each of them, despite the fact that they are exactly the same except for the 
'variantId' field. This means that the case you mention would not differ at all 
using this implementation (please correct me if I'm wrong or misunderstood 
your case).

The reference server is backed by an annotated VCF file since we cannot 
implement "on the fly annotations". Obviously this is a severe limitation on 
what we can implement in the reference server.

**Comment by sarahhunt** [comment]
@pcingola - I agree - it is cleaner even if it generates more searches as they will be more targetted and smaller. 

A new filter by VariationSet when searching for annotation sets makes sense now too. I think the filter by Dataset is probably still useful  - what do you reckon?

I'll add these updates as a PR against our branch to give you the chance to review.

**Comment by pcingola** [comment]
Great, thank you.

**Comment by david4096** [comment]
Was included in a later PR and now part of master:

https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/alleleAnnotations.avdl#L82
