### ISSUE TITLE
Variant Annotations: AlleleLocation's overlapEnd coordinate should be optional

### ISSUE THREAD

**Issue by pcingola** [ga4gh/schemas#441]
In the current schema (variant_annotations branch), AlleleLocation's overlapEnd seems 
to be a mandatory which is probably excessive. For instance, current ANN's format 
used for storing annotations in VCF files does not provide end coordinates for overlap 
within cDNA, CDS or Protein. So following this requirement would complicate server 
implementations that their back data in VCF files.

I propose to simply change the definition by making it an optional field, so the new 
record would be like this:

    record AlleleLocation {
      /** Relative start position of the allele in this coordinate system */
      int overlapStart ;
    
      /** Optional relative end position of the allele in this coordinate system  */
      union { null, int } overlapEnd ;
    
      /** Reference sequence in feature (this should be the codon at CDS level) */
      union { null, string } referenceSequence = null;
    
      /** Alternate sequence in feature (this should be the codon at CDS level) */
      union { null, string } alternateSequence = null;
    }

**Comment by AngieHinrichs** [comment]
It can be a pain to calculate missing end coordinates - but isn't the end coordinate rather important?  It seems like this would simply move the pain downstream, and would there be enough information to recalculate it?

Are you concerned that the end coordinates would be discarded in VCF?  Why not keep them in the INFO column?

**Comment by pcingola** [comment]
In today's call @sarahhunt mentioned that the field was indeed intended as optional (at 
least that's what I understood), so we wouldn't be changing the schema so much, just 
formalizing the intention.

The reason relates to the ANN field used for annotations (here is a link to the current 
ANN standard: http://snpeff.sourceforge.net/VCFannotationformat_v1.0.pdf). Using 
this ANN field, we don't have all the data required to create cDNA/CDS/protein AlleleLocation 
records, the best we can do is to make the whole entry 'null'.

I agree that the best solutions would be to: a) update the ANN standard; and/or b) not implement 
servers based on VCF files. But in the mean time, we need a schema that allows us to 
implement servers and adding non-standard INFO fields would be painful in the long run.

**Comment by AngieHinrichs** [comment]
OK, I understand.  I didn't catch the reference to "ANN" in your initial comment.

**Comment by sarahhunt** [comment]
@pcingola - sorry - I miss understood the issue on the call - this was initially meant to be a mandatory field. That said, I'm fine for it to be optional if it makes it easier for groups with annotation in VCF to adopt. (Our implementation uses a database backend or on the fly calculation so we did not hit the issue.)

**Comment by pcingola** [comment]
If you agree, can you update the schema? It's easier if you send it from your own branch.

Unfortunately the reference server is files backed implementation only.
This also means that the reference server won't have the 'on the fly' annotations.
