### ISSUE TITLE
Delete unused branches

### ISSUE THREAD

**Issue by bartgrantham** [ga4gh/schemas#465]
There's 25 branches in this repo, not including master.  Many are likely fully merged and are not needed, some may be orphaned or dead-end development efforts.  It isn't hurting anything, but it adds to the clutter.

**Comment by calbach** [comment]
In particular there are a few with @mbaudis @richarddurbin and @dglazer prefixes which should probably be forks instead (or deleted if no longer needed).

**Comment by dglazer** [comment]
I looked at dglazer-provenance -- you're right, it should be a fork instead. Is there an easy way to change it from one to the other, while there's still a PR referencing the changes? (If not I can eventually delete the PR, since it's mostly for discussion, but I'd rather not lose those diffs entirely.)

**Comment by mbaudis** [comment]
@calbach I deleted some which were clearly outdated. Will evaluate the other ones later.

**Comment by calbach** [comment]
@dglazer I'm not aware of a way to change it without losing the PR. Probably best to leave it until that issue has been closed.

**Comment by pgrosu** [comment]
Hi David,

Maybe a combination of these two might be helpful:

http://stackoverflow.com/questions/4410091/github-import-upstream-branch-into-fork

http://stackoverflow.com/questions/6022302/how-to-apply-unmerged-upstream-pull-requests-from-other-forks-into-my-fork

~p

**Comment by jeromekelleher** [comment]
I agree with @bartgrantham, lots of random branches isn't helping. Is there any way we can discourage people from making PRs via local branches, and make them use forks instead?

**Comment by calbach** [comment]
I suspect the primary cause is that the behavior of the 'edit directly in GitHub web UI' for collaborators is to create a new branch, rather than a fork. I've definitely created at least one branch this way without realizing that's what was happening.

**Comment by dglazer** [comment]
That's what happened to me -- i just followed the path of least resistance,
and ended up with a branch. Somebody scolded me and now I do it right.

**Comment by david4096** [comment]
https://github.com/ga4gh/schemas/issues/608
