### ISSUE TITLE
add a "built on" timestamp to the generated documentation

### ISSUE THREAD

**Issue by dglazer** [ga4gh/schemas#479]
@reece @diekhans -- is there a way to automatically add a timestamp to the generated doc, that says when it was built, and ideally also which branch it was built from?

**Comment by diekhans** [comment]
A timestamp and branch could easily be added to the epilog on
each page, and even the short form of hash.  However, it is is
tell what repo it came out of.

This what repo question will be answered when readthedocs is
building it automatically.

When I am working on doc, I just look at it files locally.
