### ISSUE TITLE
Create initial documentation structure in master

### ISSUE THREAD

**Issue by reece** [ga4gh/schemas#481]
During the 2015-11-06 docathon at Google, significant progress was made to create a documentation structure and tooling.  Although the documentation is not complete (i.e., not ready for release), the group believed in desirable [1] to port the doc skeleton  and build tools into master. That is the goal of this issue.

When this issue is completed, we can undertake automating the build process at either Read the Docs or on a public server elsewhere. (The choice will depend on whether the avdl-to-rst process can be cajoled into working on RTD.)

[1] https://docs.google.com/document/d/1MEEkv3V37StEV7ps8jtVnzCQxxIRz101timpOf-ZI6s/edit?ts=563d4f39

**Comment by reece** [comment]
Please assign to me or grant perms for me to assign to myself.

**Comment by diekhans** [comment]
One useful experiment to try would be to remove the use of pandoc to convert the text extracted from avdl files from markdown to restructuredtext.  We can then see what formats poorly .  It's not clear if there is much to change

**Comment by diekhans** [comment]
mvn clean no longer removes the documentation now that is  outside of the target directory in the build directory.

**Comment by diekhans** [comment]
I just tried an experiment where I removed the call to pandoc from avpr2rest.py and it produced identical output.  There may have been some markdown in the avro files that were backed out of master.  The URL syntax is more arcane:

   \`Dataset objects <../schemas/metadata.html#avro.Dataset>\`_.
vs
    \[Dataset objects\] \(../schemas/metadata.html#avro.Dataset>\)

this doesn't seem like it's a huge disadvantage compared to using one format

**Comment by reece** [comment]
I'm glad you did that test! Let's plan to drop avpr2rest.py in the documentation branch.

This issue is about just getting the basic outline and tooling into master. It doesn't involve avpr2rest.py (but does require avrodomain.py). A PR is coming in a moment.

Docs are built in target/doc/html. And -- yay! -- RTD docs are now built automatically (elapsed time ~60s).

**Comment by dglazer** [comment]
Great to see the progress here -- thank you Reece -- looking forward to +1'ing the PR.

**Comment by diekhans** [comment]
Actually I still used avpr2rest just removed the use of pandoc.  Will pr it tomorrow

-- Sent from my computer phone

-----Original Message-----
