### ISSUE TITLE
Create topic branch set for proto3

### ISSUE THREAD

**Issue by calbach** [ga4gh/schemas#486]
Following the process defined [here](https://github.com/ga4gh/schemas/blob/master/CONTRIBUTING.md#topic-branches), though I am a collaborator in this repo so I suppose I could go ahead and just create a branch myself. Who is in charge of creating these? @skeenan maybe?

**Comment by jeromekelleher** [comment]
I've created the ``protobuf`` branch [here](https://github.com/ga4gh/schemas/tree/protobuf).

**Comment by skeenan** [comment]
Yes, creating branch yourself was the right thing to do.
