### ISSUE TITLE
Request for comments: Sequence Annotations doc

### ISSUE THREAD

**Issue by calbach** [ga4gh/schemas#497]
The following document contains a draft design proposal for GA4GH sequence annotations:

https://docs.google.com/document/d/1ITQMvA0HEqXirPvQglE8bwk5W1GXYkPGb_cCz0NLnxE/edit?usp=sharing

Please comment or make suggestions on the document - I've given comment access to the ga4gh DWG Google groups that I know of. If I missed you, please just request comment access and I'll be happy to grant it (or let me know of a group that I missed).

Note that per the 'status' section at the top of the document, some parts of the proposal are more complete than others. **Please prefer commenting in the doc for content-related issues**, as it will be easier to maintain discussions there than on a single linear GitHub issue. 
## Why a doc/proposal now?
- The primary aim is to use the doc to converge on an API design which most parties are happy to implement, especially those who intend to serve data and production traffic.
- The doc will capture design decisions and rationale in detail, and it can be linked to and/or contents can be copied into the existing ga4gh documentation.
- Once the doc is finalized, there should be general agreement on a path forward for sequence annotations in all three of the ga4gh repositories.
- Multiple ga4gh parties are building on top of the existing sequence annotations draft branch, and we should make sure these use cases are accounted for in the design or be explicit about which use cases are out of scope. 
## How does this relate to the existing sequence annotations branch?
- The current proposal is quite similar to the existing branch.
- Once finalized and agreed upon, the delta between the doc and the existing branch should be translated into a PR.
-  The primary addition to the existing branch will be improved documentation and design rationale, by virtue of having a doc.

The proposal thus-far has been a joint effort between @andrewyatz, @dglazer, @dzerbino, @sarahhunt, Magali Ruffier (EBI), and myself.

**Comment by david4096** [comment]
Closing as we have https://github.com/ga4gh/schemas/blob/master/src/main/proto/ga4gh/sequence_annotation_service.proto

Thanks a ton @calbach !
