### ISSUE TITLE
ExternalIdentifier not used anywhere currently

### ISSUE THREAD

**Issue by macieksmuga** [ga4gh/schemas#512]
I noticed this while writing up the 0.6 change log: `ExternalIdentifier` (defined in `common.avdl`) is not currently used within any other record or method. I believe it came from the Sequence Annotation world, so it'll shortly be rejoining us here... but I want to confirm - is it useful in present guise? Should we consider replacing it with an equivalent record when sequence annotations get merged in?

**Comment by diekhans** [comment]
lets get an alpha out then figure out what to do.

**Comment by mbaudis** [comment]
@macieksmuga May be a remnant from earlier metadata incarnations, now, tentatively, replaced with ```accessions``` for all kinds of non-reference IDs.

**Comment by david4096** [comment]
The G2P branch is using external identifiers as part of their queries as well.

**Comment by diekhans** [comment]
this is now used

**Comment by mbaudis** [comment]
@diekhans Where, actually? Because externalIdentifier or such is one of those objects with ubiquitous scope.
