### ISSUE TITLE
Docs polluted by common.avdl

### ISSUE THREAD

**Issue by david4096** [ga4gh/schemas#554]
In readthedocs the common records, even when unused, end up in the resulting doc.

https://ga4gh-schemas.readthedocs.org/en/latest/schemas/referencemethods.html#avro.SearchReferencesRequest

Here we see CigarUnit even though I believe it is used only by reads.avdl.

**Comment by diekhans** [comment]
This is a know problem that will be fixed with the conversion to
protocol buffers.

I don't think there is another ticket on this.

**Comment by diekhans** [comment]
this will be address a part of https://github.com/ga4gh/schemas/pull/547

**Comment by david4096** [comment]
Closed with the protobuf based documentation generation. https://github.com/ga4gh/schemas/blob/7a37d81dc1bd68da7e703571e60a279b739b5388/tools/sphinx/protobuf-json-docs.py
