### ISSUE TITLE
Rename GET endpoints

### ISSUE THREAD

**Issue by david4096** [ga4gh/schemas#558]
Currently GET endpoints use the plural version of the object desired, `callsets`, `variants`, and so on:

    http://ga4gh/variants/myvariantID

I'm posting this issue to see if there's any traction to rename the GET endpoints to the singular `callset`, `variant`, etc. This gives more readable semantics: when performing a GET request at these endpoints a *single item* for that ID is returned. The above address would instead appear as:

    http://ga4gh/variant/myvariantID

When making a fully qualified GET request only a single item (or 404) will be returned, so the singular noun makes more sense.

**Comment by calbach** [comment]
The standard REST convention is GET /resources/\<resource_id\>, but I guess we can avoid any discussions about REST and just make the argument by existing precedent. I don't see any concrete reason to change the existing behavior unless there is rationale beyond personal preference; for the record, my personal preference is definitely `/variants/myVariantID`.

**Comment by diekhans** [comment]
Clear terminology should be a matter of personal preference. 

I this case, I very much think the plural terminology is correct and clear. The variants gets retrieves  a single object from of multiple objects (the resources)
