### ISSUE TITLE
read retrieval is defined in a way that is very difficult efficiently implemented

### ISSUE THREAD

**Issue by diekhans** [ga4gh/schemas#569]
SearchReadsRequest  in
https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/readmethods.avdl

is defined to require returning reads across multiple ReadGroupSets sorted by chromosome location.

This potentially requires a sort/merge of reads across tens of thousands of BAMs.

I don't know of any use cases that would require this.  Sorting is normally only within a BAM/ReadGroupSet.   

Until there is a streaming API,  a single request that cross ReadGroupSets/BAMs makes little since.

**Comment by vadimzalunin** [comment]
Limit the scope to single BAM/ReadGroupSet?

**Comment by diekhans** [comment]
Absolutely one BAM.  Apparently the was strong argument against
this limit before, but it suspect it was conflated with other
issues.

**Comment by calbach** [comment]
See: https://github.com/ga4gh/schemas/pull/253#discussion_r26700450

**Comment by diekhans** [comment]
determine that this is not an issue, but reasonable for search to put restrictions on how wide a request to support.
