### ISSUE TITLE
Implement sequence annotation in schema

### ISSUE THREAD

**Issue by kozbo** [ga4gh/schemas#573]

**Comment by diekhans** [comment]
There are some tricky issues that need to be addressed with query by name.  With GFF3 files, the concept of name varies between annotation set.

**Comment by kozbo** [comment]
Are there other tricky issues?

**Comment by diekhans** [comment]
Tons of tricky issues, generic data structure representing complex
stuff.  More will appear as we use it.


http://www.sequenceontology.org/gff3.shtml

**Comment by macieksmuga** [comment]
But is anything blocking us from accepting the sequence annotation schema draft as it appears now?

**Comment by macieksmuga** [comment]
As far as I can tell, we're done with this one.
