### ISSUE TITLE
Biodata

### ISSUE THREAD

**Issue by david4096** [ga4gh/schemas#574]
This issue is meant to track ongoing discussion for the preliminary biodata api.

It is proposed that two endpoints, `/biosamples` and `/individual`, be added. The `sampleId` field in reads and callsets will be replaced by bioSampleId, which maps to a single bioSample record available from the bioSample endpoint. These BioSamples can then have a many-to-one relationship with individuals.

BioSamples are filterable by `name` and `individualId` and can optionally have a disease associated with them.

Individuals can also be filtered by name.

Workflow example

  1) Search for an individual by name at the `/individuals` endpoint.
  2) Filter bioSample by the discovered `individualId`.
  3) Filter callsets for the discovered `bioSampleId`.

Merged PR with BioSample #559

**Comment by mbaudis** [comment]
+1 ... since this is the number agreed upon.

**Comment by david4096** [comment]
https://github.com/ga4gh/schemas/pull/579

**Comment by kozbo** [comment]
bump, this issue looks complete. Shall we close it @david4096 @mbaudis ?

**Comment by mbaudis** [comment]
Yes; this looks overripe.
