### ISSUE TITLE
readthedocs broken for `latest'

### ISSUE THREAD

**Issue by diekhans** [ga4gh/schemas#587]
In http://ga4gh-schemas.readthedocs.org/en/latest/api/references.html,
there is a link for "See References schema for a detailed reference.",
http://ga4gh-schemas.readthedocs.org/en/latest/schemas/refernces.html
which does not exist.

**Comment by pgrosu** [comment]
http://ga4gh-schemas.readthedocs.org/en/latest/schemas/references.html

Works with an `e` between `r` & `n` ;)

**Comment by diekhans** [comment]
this was fixed but not closed
