### ISSUE TITLE
TranscriptEffect CDSLocation naming consistency and feature

### ISSUE THREAD

**Issue by diekhans** [ga4gh/schemas#589]
"CDSLocation" should be named "cdsLocation" to be consistent with the rest of the API.

A featureId of the CDS feature would provide useful context

**Comment by sarahhunt** [comment]
@diekhans - #600 updates the name in the schema. 

The TranscriptEffect record is deliberately minimal at the moment. The idea is that information which can be derived from the Transcript Feature should not be included. It will be easier to see how well this works when the initial sequence annotations are available, so we can revisit.
