### ISSUE TITLE
References replace NCBI Taxon ID with Ontology Term

### ISSUE THREAD

**Issue by david4096** [ga4gh/schemas#612]
The current reference model uses the NCBI taxon ID to define the species of a record. Should this be changed to an Ontology Term?

https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/references.avdl#L69

**Comment by mbaudis** [comment]
Yes. One uniform way to deal with ontologies seems logical. Hypothetically there could be different use cases not coverd by NCBI (e. g. bacterial OTUs?), or future transitions.

**Comment by diekhans** [comment]
Is there a species ontology?  Even if there is, NCBI taxon id is use so widely that is needs to be supported.  It's still not perfect, it only reflects data submitted to NCBI and not all groups agree with the taxonomy.  Genome 10K had to collect taxonomies from multiple sources.

**Comment by mbaudis** [comment]
I'm all for a standard structure, using OntologyTerm with recommendation/example NCBI. See comment above. 
Also, by default one should not bind a schema to a specific resource which may be "transitional", even if current default.

**Comment by diekhans** [comment]
@mbaudis, I see no solid proposal above.  I am all for flexibility if it works.

**Comment by david4096** [comment]
I added this issue while working with the bioMetadata schemas. Note we use an Ontology Term for species there, which suggested to me that references could be improved with the same feature.

https://github.com/ga4gh/schemas/blob/biodataproto/src/main/proto/ga4gh/bio_metadata.proto#L38

**Comment by pgrosu** [comment]
I think `OntologyTerm` allows for the flexibility of referencing derived sequences, which allows for having a more precise way of traversing a path of the provenance of a sequence.  If we align to a path of a variant graph, that would be a derived reference sequence.
