### ISSUE TITLE
API specification allows non-unique reference names in a reference set

### ISSUE THREAD

**Issue by diekhans** [ga4gh/schemas#617]
The documentation specifically allows for multiple reference names in a reference set.  Variants and reads link via reference names to a single reference.  It's also massively confusing to have two `chr1' chromosomes in a single reference set.

Reference should be document to require name a name to be unique withing a reference set.  Also update the intro documentation to indicate that some collections require unique names.

related to https://github.com/ga4gh/schemas/issues/518

**Comment by jeromekelleher** [comment]
Definitely +1 on this! Can you give a link to the current docs where it says this please?
