### ISSUE TITLE
Schema diagram?

### ISSUE THREAD

**Issue by will-fitzhugh** [ga4gh/schemas#618]
Hi, is there a schema diagram for the objects in the GA4GH schema? I think it would really help to have something like to communicate how all the entities relate to one another.

If there isn't, I'd be happy to make one :)

Thanks,

Will

**Comment by ying-w** [comment]
I believe there was one done for variants [here](https://github.com/ga4gh/schemas/tree/master/doc/source/_static) but none exist for the entire GA4GH

**Comment by saupchurch** [comment]
@adamnovak wrote code to make a UML. See PR #297

**Comment by adamnovak** [comment]
It has since been dramatically expanded and improved by@malisas and turned
into https://github.com/malisas/schema-uml which produces much better
diagrams and also now supports Protobuf.

See for example
https://github.com/malisas/schema-uml/blob/master/avro2uml/example_svgs/everything_edited_2016-03-13.svg

**Comment by malisas** [comment]
Yep, the Avro and Protobuf versions both work now (I've been meaning to share my work with GA4GH but never got around to it).

Please let me know if some of the instructions are unclear or don't work for your system (I've only tested on Ubuntu 14.04). I'm also happy to take suggestions/collaborate on making the code better, and I'll take diagram requests as well.

The current protobuf ga4gh schema uml is [here](https://cdn.rawgit.com/malisas/schema-uml/master/protobuf2uml/example_svgs/ga4gh_2016-04-14.svg). You can click on the grey clusters to go to the corresponding file.

**Comment by will-fitzhugh** [comment]
thanks for all the comments, that diagram is very helpful!

**Comment by david4096** [comment]
@malisas does it make sense to include your work with the ga4gh-schemas? @will-fitzhugh given you've found what you're looking for would it be OK to close this?

**Comment by will-fitzhugh** [comment]
Yes, thanks for the ping. Closing.

**Comment by malisas** [comment]
Sure, maybe I can put it in the tools folder? I'll try to clean up the code in the next few weeks and submit a PR.

**Comment by diekhans** [comment]
if you point me at the program, I might be able to make suggestions
on location and integration
