### ISSUE TITLE
ANN to TranscriptEffect field correspondence

### ISSUE THREAD

**Issue by GuilhemSempere** [ga4gh/schemas#623]
Hi !

My colleague and I are having doubts implementing a REST service meant to return functional annotations in ANN format from a VCF file. This data is typically added by SnpEff. We are actually trying to find out how each of the VCF fields fits in the objects defined via the allele annotation schema.

Our mapping looks like this so far (right-hand field names based on the structure of the TranscriptEffect class):

Allele -> alternateBases
Annotation -> effects[0].term (may we have several terms in this list?)
Annotation_Impact -> ?
Gene_Name -> ?
Gene_ID -> ?
Feature_Type -> ?
Feature_ID -> featureId
Transcript_BioType -> ?
Rank -> ?
HGVS.c / HGVS.p -> hgvsAnnotation.genomic / hgvsAnnotation.protein
cDNA.pos / cDNA.length -> cDNALocation.start / cDNALocation.end
CDS.pos / CDS.length -> CDSLocation.start / CDSLocation.end
AA.pos / AA.length -> proteinLocation.start / proteinLocation.end
Distance -> ?
ERRORS/WARNINGS/INFO -> ?

We are tempted to feed the “info” map in VariantAnnotation with all the fields that we could not find an equivalent for, but we have the feeling that we are missing something.

Can someone please clarify this for us? Thanks in advance,

Guilhem

**Comment by david4096** [comment]
The info field is an effort to capture the other bits of data that don't have named fields in the schema. However, it seems like in your case there are elements of individual transcript effects you would prefer to represent alongside the transcript effect itself. A temporary workaround could be to add to the info field any details about the transcript effect by using the transcript effect ID. For example, in the case of distance you might try `annotation.info[transcriptEffectId + "distance"] = distance`.

An alternative solution would be to propose an `info` field at the level of the transcript effect. This would allow these data to be better represented in the schema.

**Comment by david4096** [comment]
@GuilhemSempere with the addition of the `info` field to transcript effect messages one should be able to interchange arbitrary key:value pairs. Our general approach is to add named fields to messages as needed. Please let me know if you think we can close this issue!

**Comment by GuilhemSempere** [comment]
Yes, this solution suits our needs, you can close the issue. Thanks!
