### ISSUE TITLE
Updating the version number of schemas

### ISSUE THREAD

**Issue by macieksmuga** [ga4gh/schemas#629]
They're still at `0.6.0-SNAPSHOT` in the `POM.xml`. Time to change this... but to what? Should we consider these as 0.7 revision schemas, or are we still at 0.6.x?

**Comment by diekhans** [comment]
We haven't done 6.0 yet.  It's all alpha.

I would like stick to alpha releases until we demonstrate we
have gained some maturity.  We need to have some confidence that it's
right through use.  We don't want people prematurely worrying about
backwards compatiblity.

**Comment by macieksmuga** [comment]
Ok, I'm closing this issue, pending de-alphaification.
