### ISSUE TITLE
``message_create_time`` inconsistent and ambiguous in Experiment

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/schemas#637]
Creating an issue to avoid side tracking PR636, https://github.com/ga4gh/schemas/pull/636#discussion_r67723063

> Why message_create_time here? The work message seems ambiguous, i.e., does this refer to the individual message objects as they are being sent to the client, or to the 'record' that is stored on the server? I'm guessing that this is because of a clash with run_time? I would have thought it would be better to just use created and updated just for the sake of being consistent with all the other objects (and change them all in one go to something more specific like creation_timestamp, update_timestamp, if/when this is done).

**Comment by diekhans** [comment]
also the use of the term `message_' is confusing.  It needs to be abstracted.

generally, all of the time fields are not documented clearly.  We need to clean this
up.

**Comment by mbaudis** [comment]
This was again mentioned in https://github.com/ga4gh/schemas/issues/682  and is being addressed in  https://github.com/ga4gh/schemas/pull/690. Closing.
