### ISSUE TITLE
Questionable use of snake_case (bio_sample_id instead of biosample_id)

### ISSUE THREAD

**Issue by mbaudis** [ga4gh/schemas#684]
The use of snake case here is confusing, since `BioSample` is a first class object. This probably comes from the confusing use of camelCase for the `BioSample` object name. Since we generally accept "biosample" as proper noun and use it as such in the documentation (this is also the case in major resources), I propose we change:
- `BioSample` => `Biosample`
- `bio_sample_id` => `biosample_id`

**Comment by dcolligan** [comment]
+1

**Comment by kozbo** [comment]
+1
