### ISSUE TITLE
Retaining sample data with RNA quantifications

### ISSUE THREAD

**Issue by david4096** [ga4gh/schemas#704]
The current RNA offering uses the Reads API to connect to sample information. This means that in order to find whether a given RNA quant is about this, or that sample, one must also host the read groups. This is problematic because there are many use cases that do not require the reads to be present.

Let's add a biosample ID to the RnaQuantification message. This redundancy does very little to increase data size but will greatly improve the usefulness of the endpoint. Currently, in the absence of reads, clever naming is the only method one has for identifying whether a quantification arrived from a specific sample. @saupchurch

**Comment by mbaudis** [comment]
+1

**Comment by david4096** [comment]
Closed with https://github.com/ga4gh/schemas/pull/705
