### ISSUE TITLE
Multiple Ontology Term URIs

### ISSUE THREAD

**Issue by david4096** [ga4gh/schemas#708]
From https://github.com/ga4gh/schemas/pull/694

Ontology Terms can be represented by multiple unique URIs. Perhaps we should allow multiple `term_uris` to be defined for any Ontology Term?

@jmcmurry added a line comment 4 hours ago

> If multiple discrepant URIs exist and are known, what is the plan for describing / collapsing them?

**Comment by mbaudis** [comment]
-1 on this.

I am not sure how this would be of any benefit - iterating through the if one doesn't resolve? But then, which precedence? This should better be addressed captured through a service which remaps ontologies/URIs of moved/deprecated end points.

**Comment by mcourtot** [comment]
I would recommend not to. Instead, as per https://github.com/ga4gh/schemas/issues/695, we'll rely on an external registry. Note that this may imply we remove the termURI attribute at a next iteration, but would provide greater flexibility to redirect towards active resolvers.

**Comment by david4096** [comment]
@jmcmurry care to comment?

**Comment by jmcmurry** [comment]
No perfect solution but agree w/ @mcourtot that reliance on OLS is the way to go. Any objections? How close are they to having API access to their registry?

**Comment by mcourtot** [comment]
Pinging @simonjupp. Note this relates to the discussion during the Vancouver meeting and at https://github.com/ga4gh/schemas/pull/694.
In short, we decided to keep CURIE + label to denote ontology terms and remove other attributes.
