### ISSUE TITLE
Highly misleading comments in  schemas/src/main/proto/ga4gh/genotype_phenotype_service.proto

### ISSUE THREAD

**Issue by shadowtramp** [ga4gh/schemas#719]
The file  schemas/src/main/proto/ga4gh/genotype_phenotype_service.proto
 contains highly misleading comment sections, specifying, that most search methods return instance of SearchPhenotypeAssociationSetsResponse, while methods SearchPhenotype and SearchPhenotypeAssociations have prototypes. returning different messages.

**Comment by bwalsh** [comment]
@shadowtramp thanks very much for the feedback.   Can you review change?

**Comment by shadowtramp** [comment]
Thanks! That fixes it.
Do I need to do some formal reviewing somehow?

**Comment by bwalsh** [comment]
@shadowtramp  Thanks for the quick turn around.   That should do it.
@kozbo Should be ok for merge.

**Comment by kozbo** [comment]
@shadowtramp We will count that as your +1 :-)
