### ISSUE TITLE
Release Schema to PyPi

### ISSUE THREAD

**Issue by david4096** [ga4gh/schemas#721]
Some release automation for putting the compiled protobuf classes in PyPi would be helpful. This would allow folks to `import ga4gh` and have access to the compiled classes in their software.

**Comment by dcolligan** [comment]
We've got the next best thing for right now: `import ga4gh_schemas`: https://pypi.python.org/pypi/ga4gh-schemas

**Comment by dcolligan** [comment]
The repo that the package is released out of is here: https://github.com/dcolligan/ga4gh-schemas

Based on this schemas branch: https://github.com/ga4gh/schemas/pull/731

And currently used in the client: https://github.com/ga4gh/ga4gh-client

I'll wait until the schemas PR is accepted and my personal schemas repo moved under the ga4gh organization before closing this issue.

**Comment by david4096** [comment]
Nearly closed with https://github.com/ga4gh/schemas/pull/744, just need to add some python specific documentation on usage, and release process.

**Comment by kozbo** [comment]
closed in favor of #753
