### ISSUE TITLE
Inconsistency - Typo

### ISSUE THREAD

**Issue by achave11** [ga4gh/schemas#722]
In all the requests for get elements by id. There is a pattern for both GET and POST method the only thing that changes is the `/search` or `/{element_id}` found `/rnaquantification/{rna_quantification_id}` `inconsistent with /rnaquantifications/search` 
https://github.com/ga4gh/schemas/blob/master/src/main/proto/ga4gh/rna_quantification_service.proto#L148

**Comment by david4096** [comment]
Thanks! It looks like the comment is incorrect, however, the actual annotations are the way you describe. Namely, `rnaquantifcations/{rna_quantification_id}` https://github.com/ga4gh/schemas/blob/master/src/main/proto/ga4gh/rna_quantification_service.proto#L51 .
