### ISSUE TITLE
Call schema not suited for variant calls with no coverage

### ISSUE THREAD

**Issue by Welliton309** [ga4gh/schemas#727]
As recommended by @dcolligan, I am adding this issue here to describe a problem that I found on GA4GH schemas and was first described at ga4gh/server#1389.

When the VCF file has variant calls with no coverage represented by `./.` the GA4H API server cannot convert this data to the appropriated value. The solution I found was change [this line](https://github.com/ga4gh/schemas/blob/master/src/main/proto/ga4gh/variants.proto#L121) to:

```
google.protobuf.ListValue genotype = 3;
```

After compiled protobuf files and updated the server it worked fine.

**Comment by mbaudis** [comment]
+1

... or more. Anonymous positions are necessary for structural variants, which frequently are imprecise and without any utility for providing the reference base.

**Comment by kozbo** [comment]
@david4096 any reason to wait on a PR to close this out?

**Comment by mbaudis** [comment]
@kozbo @david4096 This is handled by https://github.com/ga4gh/schemas/pull/735/files#diff-70572e12d3d541d3f4fbdd23c76ebb64 . I've just added some more doc there. Should be merged ASAP...
