### ISSUE TITLE
Repo Manager GUI

### ISSUE THREAD

**Issue by david4096** [ga4gh/schemas#749]
By exposing the repo manager functionality over the web, we can develop user interfaces that make administering data sources much easier. The primary desire is to be able to add, remove, and alter hosted data without much struggle. This will make it easier to manage a server by separating out maintenance and data tasks.

Update functionality will have to be added to the data repo to allow tagging of Callsets with Biosample data.

**Comment by ejacox** [comment]
As part of this effort, the repo manager code can be separated from the server code, creating a cleaner design.

A trade-off to keep in mind is the target audience. Experienced users can use the existing command-line repo manager. This effort targets less experienced users who would benefit from a GUI. We don't want to maintain two completely separate interfaces, though.

**Comment by david4096** [comment]
Meant https://github.com/ga4gh/server/issues/1489
