### ISSUE TITLE
Documentation generation failing

### ISSUE THREAD

**Issue by david4096** [ga4gh/schemas#757]
The doc generation process is failing due to changes moving from the protobuf beta to stable. We use two tools for generating RST documentation from protobuf that need to be updated to support this version, or an alternative solution should be found.

We need to add `make docs` to the .travis.yml.

```
Exception occurred:
  File "/home/david/git/schemas/env/local/lib/python2.7/site-packages/docutils/writers/_html_base.py", line 672, in depart_document
    assert not self.context, 'len(context) = %s' % len(self.context)
AssertionError: len(context) = 1
The full traceback has been saved in /tmp/sphinx-err-eTK5l1.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:31: recipe for target 'docs' failed
make: *** [docs] Error 1
(env) ➜  schemas git:(maste
```

**Comment by david4096** [comment]
Was unrelated to our changes, a bug in docutils https://github.com/sphinx-doc/sphinx/issues/3212 . We can fix our build process, but readthedocs is currently still failing.

**Comment by kozbo** [comment]
RTD is now passing. Closing
