### ISSUE TITLE
Add ability to list and join peer server networks

### ISSUE THREAD

**Issue by kozbo** [ga4gh/schemas#760]
The GA4GH APIs facilitate the interoperable exchange of genomic information but there currently is no way to easily find servers that are supporting the GA4GH APIs as a service. What is needed is a directory service that lists out all participating GA4GH servers. This [specification](https://docs.google.com/document/d/1hc-l7P0S0G8j19n0dKV9e0AeF8zgE3I88fNveSC178w/edit#) describes a few protocol additions that will facilitate the following capabilities:
   * join a list of peers on another service
   * report on a list of peers maintained by this service
   * return version information about the current server

**Comment by sarahhunt** [comment]
Hi @kozbo - sounds interesting, but I don't have permission to view the spec - should it be public?

**Comment by kozbo** [comment]
@sarahhunt Thanks for pointing that out. I have changed the permissions to allow anyone to comment. Let me know if you still cannot access the spec.
