### ISSUE TITLE
Can we come up with a shorter name for reference sequences?

### ISSUE THREAD

**Issue by cassiedoll** [ga4gh/schemas#88]
`GAReferenceSequenceSet` and all of its friends are quite wordy. Can we come up with a shorter name for these objects?

Possibly: `ReferenceSet` (which would mean `Reference`, /referencesets/search, etc)

or is there another option perhaps? (I kinda liked contig, but I know that probably won't work :)

**Comment by richarddurbin** [comment]
I have sent you a fax message. Please check document attached.
</html
